// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phoneNumbers: ["+12345678901", "+19876543210"]
 *     }
 */
export interface RcsCapabilitiesQuery {
    /**
     * List of phone numbers to check RCS capabilities for (E.164 format). <br><br>
     * **Limit:** 1 min
     */
    phoneNumbers: string[];
    /** Optional RCS agent ID (prefixed with 'agent_') to check capabilities of a number from a specific agent. */
    agentId?: string;
}
