// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         agentId: "agent_XXXXXXXXXXXX",
 *         phoneNumber: "+12345678901"
 *     }
 */
export interface RcsWhitelistRequest {
    /** The RCS agent ID (must be prefixed with 'agent_') */
    agentId: string;
    /** Phone number to whitelist for testing (E.164 format) */
    phoneNumber: string;
}
