// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../core/headers.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import * as errors from "../../../../../../errors/index.js";
import * as Pinnacle from "../../../../../index.js";

export declare namespace Simulate {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Simulate {
    protected readonly _options: Simulate.Options;

    constructor(_options: Simulate.Options) {
        this._options = _options;
    }

    /**
     * Simulate inbound messages and button presses from a user.
     *
     * @param {Pinnacle.SimulateUserParams} request
     * @param {Simulate.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Pinnacle.BadRequestError}
     * @throws {@link Pinnacle.UnauthorizedError}
     * @throws {@link Pinnacle.ForbiddenError}
     * @throws {@link Pinnacle.InternalServerError}
     *
     * @example
     *     await client.messages.simulate.user({
     *         from: "+14155551234",
     *         to: "+14155555678",
     *         message: {
     *             text: "Hello from the test user!"
     *         }
     *     })
     *
     * @example
     *     await client.messages.simulate.user({
     *         from: "+14155551234",
     *         to: "+14155555678",
     *         message: {
     *             mediaUrls: ["https://example.com/image.jpg"]
     *         }
     *     })
     *
     * @example
     *     await client.messages.simulate.user({
     *         from: "+14155551234",
     *         to: "+14155555678",
     *         message: {
     *             text: "Check this out",
     *             mediaUrls: ["https://example.com/image.jpg"]
     *         }
     *     })
     *
     * @example
     *     await client.messages.simulate.user({
     *         from: "+14155551234",
     *         to: "agent_abc123",
     *         button: {
     *             type: "trigger",
     *             title: "Sign Up",
     *             payload: "user_clicked_signup"
     *         }
     *     })
     *
     * @example
     *     await client.messages.simulate.user({
     *         from: "+14155551234",
     *         to: "agent_abc123",
     *         button: {
     *             type: "openUrl",
     *             title: "Visit Website"
     *         }
     *     })
     *
     * @example
     *     await client.messages.simulate.user({
     *         from: "+14155551234",
     *         to: "agent_abc123",
     *         button: {
     *             type: "call",
     *             title: "Call Us",
     *             payload: "+15555555555"
     *         }
     *     })
     *
     * @example
     *     await client.messages.simulate.user({
     *         from: "+14155551234",
     *         to: "agent_abc123",
     *         button: {
     *             type: "scheduleEvent",
     *             title: "Add to Calendar",
     *             eventTitle: "Pinnacle Workshop",
     *             eventStartTime: "2025-12-12T10:00:00Z",
     *             eventEndTime: "2025-12-12T11:00:00Z"
     *         }
     *     })
     *
     * @example
     *     await client.messages.simulate.user({
     *         from: "+14155551234",
     *         to: "agent_abc123",
     *         button: {
     *             type: "sendLocation",
     *             title: "View Location",
     *             name: "Pinnacle HQ",
     *             latLong: {
     *                 lat: 37.7899,
     *                 lng: -122.3969
     *             }
     *         }
     *     })
     *
     * @example
     *     await client.messages.simulate.user({
     *         from: "+14155551234",
     *         to: "agent_abc123",
     *         button: {
     *             type: "requestUserLocation",
     *             title: "Share Location"
     *         }
     *     })
     */
    public user(
        request: Pinnacle.SimulateUserParams,
        requestOptions?: Simulate.RequestOptions,
    ): core.HttpResponsePromise<Pinnacle.SimulateUserResponse> {
        return core.HttpResponsePromise.fromPromise(this.__user(request, requestOptions));
    }

    private async __user(
        request: Pinnacle.SimulateUserParams,
        requestOptions?: Simulate.RequestOptions,
    ): Promise<core.WithRawResponse<Pinnacle.SimulateUserResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PinnacleEnvironment.Default,
                "messages/simulate/user",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Pinnacle.SimulateUserResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Pinnacle.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Pinnacle.UnauthorizedError(
                        _response.error.body as Pinnacle.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Pinnacle.ForbiddenError(_response.error.body as Pinnacle.Error_, _response.rawResponse);
                case 500:
                    throw new Pinnacle.InternalServerError(
                        _response.error.body as Pinnacle.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.PinnacleError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PinnacleError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PinnacleTimeoutError("Timeout exceeded when calling POST /messages/simulate/user.");
            case "unknown":
                throw new errors.PinnacleError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "PINNACLE-API-KEY": apiKeyValue };
    }
}
