// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../../../../../../index.js";

/**
 * @example
 *     {
 *         audienceId: "aud_abc123",
 *         senders: ["+14155164736", "+14155164737"],
 *         message: {
 *             mediaUrls: ["https://fastly.picsum.photos/id/941/300/300.jpg"],
 *             text: "Check out this image!"
 *         },
 *         options: {
 *             validate: true
 *         }
 *     }
 *
 * @example
 *     {
 *         audienceId: "aud_abc123",
 *         senders: ["+14155164736", "+14155164737"],
 *         message: {
 *             mediaUrls: ["https://fastly.picsum.photos/id/941/300/300.jpg"],
 *             text: "Check out this image!"
 *         },
 *         options: {
 *             validate: true
 *         }
 *     }
 */
export interface BlastMms {
    /**
     * The audience ID to send the blast to. This identifier is a string that always begins with the prefix `aud_`, for example: `aud_abc123`. <br>
     *
     * You can create an audience via [the dashboard](https://app.pinnacle.sh/dashboard/audiences) or [API](/api-reference/audiences/create).
     */
    audienceId: string;
    /**
     * Array of phone numbers to send from in E.164 format. <br>
     *
     * Messages will be distributed evenly across these senders.
     *
     * > **Note:** Sandbox numbers cannot be used for blasts.
     *
     * **Limit:** 1 min
     */
    senders: string[];
    message: Pinnacle.MmsContent;
    /** Additional settings to customize MMS blast delivery. */
    options?: BlastMms.Options;
}

export namespace BlastMms {
    /**
     * Additional settings to customize MMS blast delivery.
     */
    export interface Options {
        /**
         * Set to true to validate the message before sending. <br>
         *
         * If validation fails, the blast is not sent.
         */
        validate?: boolean;
        schedule?: Pinnacle.MessageSchedule;
    }
}
