/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Pinnacle from "../../../../api/index";
import * as core from "../../../../core";
import { CompanyUpdateResponseBrand } from "./CompanyUpdateResponseBrand";

export const CompanyUpdateResponse: core.serialization.ObjectSchema<
    serializers.CompanyUpdateResponse.Raw,
    Pinnacle.CompanyUpdateResponse
> = core.serialization.object({
    brand: CompanyUpdateResponseBrand,
});

export declare namespace CompanyUpdateResponse {
    interface Raw {
        brand: CompanyUpdateResponseBrand.Raw;
    }
}
