/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../../../../../index.js";

export type SendRcsResponse = Pinnacle.SentRcsDetails | Pinnacle.ScheduledMessaage;
