// This file was auto-generated by Fern from our API Definition.

import * as Pinnacle from "../../../src/api/index";
import { PinnacleClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("Requests", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            pageIndex: 0,
            pageSize: 20,
            type: "silent-auth",
            status: "completed",
            clientRef: "user_123",
        };
        const rawResponseBody = {
            data: [
                {
                    requestId: "nar_1234567890ABCDEF",
                    type: "silent-auth",
                    status: "completed",
                    clientRef: "user_123",
                    createdAt: "2026-06-12T18:25:00Z",
                    updatedAt: "2026-06-12T18:26:00Z",
                    completedAt: "2026-06-12T18:26:00Z",
                    expiresAt: "2026-06-12T18:30:00Z",
                    errorMessage: null,
                    result: { requestId: "nar_1234567890ABCDEF", status: "completed" },
                },
            ],
            hasMore: false,
            count: 1,
        };
        server
            .mockEndpoint()
            .post("/network/requests/list")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.network.requests.list({
            pageIndex: 0,
            pageSize: 20,
            type: "silent-auth",
            status: "completed",
            clientRef: "user_123",
        });
        expect(response).toEqual({
            data: [
                {
                    requestId: "nar_1234567890ABCDEF",
                    type: "silent-auth",
                    status: "completed",
                    clientRef: "user_123",
                    createdAt: "2026-06-12T18:25:00Z",
                    updatedAt: "2026-06-12T18:26:00Z",
                    completedAt: "2026-06-12T18:26:00Z",
                    expiresAt: "2026-06-12T18:30:00Z",
                    errorMessage: null,
                    result: {
                        requestId: "nar_1234567890ABCDEF",
                        status: "completed",
                    },
                },
            ],
            hasMore: false,
            count: 1,
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/network/requests/list")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.network.requests.list();
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/network/requests/list")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.network.requests.list();
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/network/requests/list")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.network.requests.list();
        }).rejects.toThrow(Pinnacle.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/network/requests/list")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.network.requests.list();
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            requestId: "nar_1234567890ABCDEF",
            type: "sim-swap",
            status: "completed",
            clientRef: null,
            createdAt: "2026-06-12T18:25:00Z",
            updatedAt: "2026-06-12T18:25:01Z",
            completedAt: "2026-06-12T18:25:01Z",
            expiresAt: null,
            errorMessage: null,
            result: {
                requestId: "nar_1234567890ABCDEF",
                status: "available",
                simSwapped: false,
                latestSimSwapAt: null,
            },
        };
        server
            .mockEndpoint()
            .get("/network/requests/nar_1234567890ABCDEF")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.network.requests.get("nar_1234567890ABCDEF");
        expect(response).toEqual({
            requestId: "nar_1234567890ABCDEF",
            type: "sim-swap",
            status: "completed",
            clientRef: null,
            createdAt: "2026-06-12T18:25:00Z",
            updatedAt: "2026-06-12T18:25:01Z",
            completedAt: "2026-06-12T18:25:01Z",
            expiresAt: null,
            errorMessage: null,
            result: {
                requestId: "nar_1234567890ABCDEF",
                status: "available",
                simSwapped: false,
                latestSimSwapAt: null,
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/network/requests/requestId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.network.requests.get("requestId");
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .get("/network/requests/requestId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.network.requests.get("requestId");
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .get("/network/requests/requestId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.network.requests.get("requestId");
        }).rejects.toThrow(Pinnacle.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/network/requests/requestId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.network.requests.get("requestId");
        }).rejects.toThrow(Pinnacle.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .get("/network/requests/requestId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.network.requests.get("requestId");
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });
});
