// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         code: "abc123"
 *     }
 */
export interface SilentAuthCheckRequest {
    /** Code returned by the JSON Silent Auth device flow. */
    code: string;
}
