// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../../../../index.js";

/**
 * @example
 *     {
 *         from: "from",
 *         to: "to",
 *         mediaUrl: "mediaUrl"
 *     }
 */
export interface SendFaxParams {
    /** Optional unique key for one logical send. Without it, every request creates a new fax. Use 1–128 ASCII letters, numbers, periods, underscores, or hyphens. Reuse it only with the identical `from`, `to`, `mediaUrl`, and effective `quality`; any change returns 409. */
    "Idempotency-Key"?: string;
    /** Fax-enabled, non-sandbox number owned by your HIPAA team, in E.164 format (`+` followed by 10–15 digits; the first digit cannot be zero). The number must remain enabled and configured through preparation. Fax sending is unavailable to development-mode teams. */
    from: string;
    /** Recipient fax number in E.164 format (`+` followed by 10–15 digits; the first digit cannot be zero). */
    to: string;
    /**
     * Public HTTPS URL on port 443 for one PDF, TIFF, JPEG, PNG, DOC, DOCX, RTF, or TXT document. The URL must contain 9–8,192 characters, including signed query parameters. Usernames, passwords, redirects, private or local addresses, IPv6-only hosts, and non-200 responses are rejected.
     *
     * The origin must complete the download within 30 seconds and return no more than 16 KiB of response headers. If present, `Content-Length` must be a non-negative decimal integer no greater than 50,000,000, and `Content-Type` must be one of the accepted types listed in the endpoint description. The source and processed document must each be no larger than 50,000,000 bytes. The document must contain 1–3,500 pages.
     *
     * A permitted URL extension or `Content-Type` is not sufficient: file signatures and structure must identify a supported format. JPEG/PNG images are limited to 250,000,000 pixels and TIFF images to 2,000,000,000 pixels. DOCX archives must be non-encrypted and free of macros, ActiveX controls, embedded objects, symbolic links, and unsafe paths; ZIP64 and multi-disk containers are not accepted. See the endpoint description for the complete DOCX archive and document-processing limits.
     */
    mediaUrl: string;
    /** Rendering profile applied to the fax. Defaults to `HIGH`. Higher-detail profiles can take longer to process but do not change the $0.025 per-page price or any document limit. */
    quality?: Pinnacle.FaxQualityEnum;
}
