/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         uris: ["https://server.trypinnacle.app/storage/v1/object/sign/vault/3/test.jpg?token=oldtoken", "https://server.trypinnacle.app/storage/v1/object/sign/vault/3/document.pdf?token=oldtoken2", "icons/3/test.jpg", "invalid/url", "https://google.com"]
 *     }
 */
export interface RefreshFileParams {
    /**
     * Array of file URIs to refresh for extended access. <br>
     *
     * Accepted formats:
     * - **Full presigned URLs**: `https://server.trypinnacle.app/storage/v1/object/sign/...`
     * - **Short URIs**: `{BUCKET}/${TEAM_ID}/...` (e.g., `vault/3/document.pdf`)
     *
     * Invalid or external URLs will be returned unchanged in the response.
     */
    uris: string[];
}
