/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         contentType: "image/jpeg",
 *         size: 1024,
 *         name: "test.jpg",
 *         options: {
 *             deleteAt: "2025-12-31T23:59:59Z",
 *             download: {
 *                 expiresAt: "2025-06-30T12:00:00.000Z"
 *             }
 *         }
 *     }
 */
export interface UploadFileParams {
    /**
     * MIME type of your file. <br>
     *
     * Supported file types:
     * - Audio: mp3, mp4, mpeg, ogg, aac, webm, wav, 3gpp, amr
     * - Video: mp4, mpeg, quicktime, webm, 3gpp, H.264, m4v
     * - Image: jpeg, png, gif, bmp, tiff, webp
     * - Documents: pdf, csv, rtf, calendar, vcard
     */
    contentType: string;
    /** Size of your file in bytes. Should be less than 100 MB. */
    size: number;
    /** Name of your file. */
    name?: string;
    /** Additional configurations for your file. */
    options?: UploadFileParams.Options;
}

export namespace UploadFileParams {
    /**
     * Additional configurations for your file.
     */
    export interface Options {
        /**
         * Set a deletion date for your file in ISO 8601 format. After this date, the file will be automatically deleted from our storage.<br>
         *
         * If this field is not provided, the file will not be deleted. You can still schedule deletion or delete the file manually in the Storage page in the dashboard.
         */
        deleteAt?: string;
        /** Configure download settings for your uploaded file. */
        download?: Options.Download;
    }

    export namespace Options {
        /**
         * Configure download settings for your uploaded file.
         */
        export interface Download {
            /**
             * Set an expiration date for file download access.<br>
             *
             * If this field is not provided, then a short permalink is generated instead.
             */
            expiresAt?: string;
        }
    }
}
