// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as Pinnacle from "../index.js";

export class GoneError extends errors.PinnacleError {
    constructor(body: Pinnacle.Error_, rawResponse?: core.RawResponse) {
        super({
            message: "GoneError",
            statusCode: 410,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, GoneError.prototype);
    }
}
