// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as Pinnacle from "../index.js";

export class NotImplementedError extends errors.PinnacleError {
    constructor(body: Pinnacle.Error_, rawResponse?: core.RawResponse) {
        super({
            message: "NotImplementedError",
            statusCode: 501,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, NotImplementedError.prototype);
    }
}
