/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ConversationsListMessagesRequestStatus =
    | "PENDING"
    | "SENT"
    | "SEND_FAILED"
    | "DELIVERED"
    | "DELIVERY_FAILED"
    | "RECEIVED"
    | "READ";
export const ConversationsListMessagesRequestStatus = {
    Pending: "PENDING",
    Sent: "SENT",
    SendFailed: "SEND_FAILED",
    Delivered: "DELIVERED",
    DeliveryFailed: "DELIVERY_FAILED",
    Received: "RECEIVED",
    Read: "READ",
} as const;
