/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../../../../../index.js";

export interface RcsAutofillResponse extends Pinnacle.RcsCampaign {
    brand?: number;
}
