// This file was auto-generated by Fern from our API Definition.

import * as Pinnacle from "../../../src/api/index";
import { PinnacleClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("Url", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "https://www.pinnacle.sh/", options: { expiresAt: "2025-06-23T16:18:25.000Z" } };
        const rawResponseBody = {
            url: "https://pncl.to/hJCJadm9",
            config: { to: "https://docs.pinnacle.sh/", expiresAt: "2025-06-23T16:18:25+00:00" },
        };
        server
            .mockEndpoint()
            .post("/tools/url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.url.create({
            url: "https://www.pinnacle.sh/",
            options: {
                expiresAt: "2025-06-23T16:18:25.000Z",
            },
        });
        expect(response).toEqual({
            url: "https://pncl.to/hJCJadm9",
            config: {
                to: "https://docs.pinnacle.sh/",
                expiresAt: "2025-06-23T16:18:25+00:00",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "url" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/tools/url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tools.url.create({
                url: "url",
            });
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "url" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/tools/url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tools.url.create({
                url: "url",
            });
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "url" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/tools/url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tools.url.create({
                url: "url",
            });
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            url: "https://pncl.to/ePzVxILF",
            config: { to: "https://pinnacle.sh", expiresAt: "2023-10-23T16:18:25+00:00" },
            clicks: [
                {
                    accept_language: "accept_language",
                    accuracy_radius_km: 1,
                    asn: 1,
                    blocked_reason: "blocked_reason",
                    ch_ua_brand: "ch_ua_brand",
                    ch_ua_mobile: "ch_ua_mobile",
                    ch_ua_platform: "ch_ua_platform",
                    city: "city",
                    color_depth: 1,
                    connection_type: "connection_type",
                    country: "country",
                    created_at: "2025-07-09T23:57:28.889+00:00",
                    error_details: { key: "value" },
                    fbclid: "fbclid",
                    final_url: "final_url",
                    fingerprint_id: "fingerprint_id",
                    gclid: "gclid",
                    ip_address: "ip_address",
                    ip_chain: ["ip_chain"],
                    is_bot: false,
                    latency_ms: 400,
                    latitude: 1.1,
                    longitude: 1.1,
                    metadata: { key: "value" },
                    method: "GET",
                    metro_code: 1,
                    network_downlink: 1.1,
                    network_rtt: 1,
                    performance_ttfb_ms: 1,
                    postal_code: "postal_code",
                    redirect_hops: 0,
                    referrer: "referrer",
                    referrer_domain: "referrer_domain",
                    region: "region",
                    resolved_at: "resolved_at",
                    screen_res: "screen_res",
                    status_code: 302,
                    timezone_offset_min: 1,
                    tor_exit_node: true,
                    ua_browser: "ua_browser",
                    ua_device: "ua_device",
                    ua_os: "ua_os",
                    ua_version: "ua_version",
                    user_agent: "vscode-restclient",
                    utm_campaign: "utm_campaign",
                    utm_content: "utm_content",
                    utm_medium: "utm_medium",
                    utm_source: "utm_source",
                    utm_term: "utm_term",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/tools/url/ePzVxILF")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.url.get("ePzVxILF");
        expect(response).toEqual({
            url: "https://pncl.to/ePzVxILF",
            config: {
                to: "https://pinnacle.sh",
                expiresAt: "2023-10-23T16:18:25+00:00",
            },
            clicks: [
                {
                    accept_language: "accept_language",
                    accuracy_radius_km: 1,
                    asn: 1,
                    blocked_reason: "blocked_reason",
                    ch_ua_brand: "ch_ua_brand",
                    ch_ua_mobile: "ch_ua_mobile",
                    ch_ua_platform: "ch_ua_platform",
                    city: "city",
                    color_depth: 1,
                    connection_type: "connection_type",
                    country: "country",
                    created_at: "2025-07-09T23:57:28.889+00:00",
                    error_details: {
                        key: "value",
                    },
                    fbclid: "fbclid",
                    final_url: "final_url",
                    fingerprint_id: "fingerprint_id",
                    gclid: "gclid",
                    ip_address: "ip_address",
                    ip_chain: ["ip_chain"],
                    is_bot: false,
                    latency_ms: 400,
                    latitude: 1.1,
                    longitude: 1.1,
                    metadata: {
                        key: "value",
                    },
                    method: "GET",
                    metro_code: 1,
                    network_downlink: 1.1,
                    network_rtt: 1,
                    performance_ttfb_ms: 1,
                    postal_code: "postal_code",
                    redirect_hops: 0,
                    referrer: "referrer",
                    referrer_domain: "referrer_domain",
                    region: "region",
                    resolved_at: "resolved_at",
                    screen_res: "screen_res",
                    status_code: 302,
                    timezone_offset_min: 1,
                    tor_exit_node: true,
                    ua_browser: "ua_browser",
                    ua_device: "ua_device",
                    ua_os: "ua_os",
                    ua_version: "ua_version",
                    user_agent: "vscode-restclient",
                    utm_campaign: "utm_campaign",
                    utm_content: "utm_content",
                    utm_medium: "utm_medium",
                    utm_source: "utm_source",
                    utm_term: "utm_term",
                },
            ],
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/tools/url/linkId").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tools.url.get("linkId");
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/tools/url/linkId").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tools.url.get("linkId");
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/tools/url/linkId").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tools.url.get("linkId");
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { url: "https://www.pinnacle.sh/" };
        const rawResponseBody = {
            url: "https://pncl.to/hJCJadm9",
            config: { to: "https://www.pinnacle.sh/", expiresAt: "2025-06-23T16:18:25+00:00" },
        };
        server
            .mockEndpoint()
            .put("/tools/url/ePzVxILF")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.url.update("ePzVxILF", {
            url: "https://www.pinnacle.sh/",
        });
        expect(response).toEqual({
            url: "https://pncl.to/hJCJadm9",
            config: {
                to: "https://www.pinnacle.sh/",
                expiresAt: "2025-06-23T16:18:25+00:00",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/tools/url/linkId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tools.url.update("linkId");
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .put("/tools/url/linkId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tools.url.update("linkId");
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .put("/tools/url/linkId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tools.url.update("linkId");
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });
});
