/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Pinnacle from "../../../../../api/index";
import * as core from "../../../../../core";

export const SendMmsRequest: core.serialization.Schema<serializers.SendMmsRequest.Raw, Pinnacle.SendMmsRequest> =
    core.serialization.object({
        to: core.serialization.string(),
        from: core.serialization.string(),
        text: core.serialization.string().optional(),
        mediaUrls: core.serialization.list(core.serialization.string()),
    });

export declare namespace SendMmsRequest {
    interface Raw {
        to: string;
        from: string;
        text?: string | null;
        mediaUrls: string[];
    }
}
