// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../index.js";

/**
 * Free-form text input backed by a client-side Google Places autocomplete. Shares text-field validation (length / pattern); the place lookup happens entirely in the browser and is purely for suggestion UX.
 */
export interface AddressField extends Pinnacle.FieldBase {
    /** Ghost text shown inside the input while it's empty. */
    placeholder?: string;
    /** Regex the value must match. Same RE2 safety check as `TextField.pattern`. Rarely needed for addresses — usually left off. */
    pattern?: string;
    /** Minimum number of characters in the selected address. */
    min_length?: number;
    /** Maximum number of characters in the selected address. */
    max_length?: number;
}
