/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Details of a phone number that has been successfully purchased and provisioned.
 * Includes all communication capabilities currently enabled for immediate use.
 */
export interface BuyResponse {
    /** Purchased phone number in E.164 format. */
    number: string;
    /** Enabled communication features for the phone number. */
    capabilities: BuyResponse.Capabilities;
}

export namespace BuyResponse {
    /**
     * Enabled communication features for the phone number.
     */
    export interface Capabilities {
        /** Indicates if SMS messaging is enabled and functional. */
        sms: boolean;
        /** Indicates if multimedia messaging (images, videos, files) is enabled and functional. */
        mms: boolean;
        /** Indicates if voice calling is enabled and functional. */
        voice: boolean;
    }
}
