// This file was auto-generated by Fern from our API Definition.

/**
 * Direction of the call relative to your Pinnacle team.
 *
 * - `INBOUND`: The call originated from an external caller and was received by one of your Pinnacle voice-enabled phone numbers.
 * - `OUTBOUND`: The call was created from Pinnacle and dialed out from one of your voice-enabled phone numbers.
 */
export const CallDirection = {
    Inbound: "INBOUND",
    Outbound: "OUTBOUND",
} as const;
export type CallDirection = (typeof CallDirection)[keyof typeof CallDirection];
