// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../index.js";

export interface Call {
    id: string;
    state: Pinnacle.CallState;
    direction: Pinnacle.CallDirection;
    to: string | null;
    from: string | null;
    created_at: string;
    started_at: string | null;
    answered_at: string | null;
    ended_at: string | null;
    metadata: Record<string, string>;
    recording_state: Pinnacle.RecordingState | null;
    hangup_cause: string | null;
    /** Present on create responses and echoes the requested create-time recording option. */
    record?: boolean;
}
