// This file was auto-generated by Fern from our API Definition.

/**
 * Current voice call lifecycle state. This field is named `state` on Call objects and `status` on `CALL.STATUS` webhook payloads.
 *
 * - `INITIATED`: Pinnacle accepted the call request and is setting up the call with the voice provider.
 * - `RINGING`: The call is ringing and has not been answered yet.
 * - `ANSWERED`: The call has been answered and is active.
 * - `BRIDGED`: The call is connected to another call leg, such as after a transfer or bridge command.
 * - `ENDED`: The call ended normally.
 * - `FAILED`: The call could not be established or could not continue because of a provider or system failure.
 * - `NO_ANSWER`: The call rang until timeout without being answered.
 * - `BUSY`: The destination was busy.
 * - `CANCELED`: The call was canceled before normal completion.
 */
export const CallState = {
    Initiated: "INITIATED",
    Ringing: "RINGING",
    Answered: "ANSWERED",
    Bridged: "BRIDGED",
    Ended: "ENDED",
    Failed: "FAILED",
    NoAnswer: "NO_ANSWER",
    Busy: "BUSY",
    Canceled: "CANCELED",
} as const;
export type CallState = (typeof CallState)[keyof typeof CallState];
