/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CampaignSubmission {
    /** Indicates whether the campaign submission was successful. */
    success: boolean;
}
