// This file was auto-generated by Fern from our API Definition.

/**
 * The type of campaign:
 * - TOLL_FREE: Toll-free number campaigns
 * - 10DLC: 10-digit long code campaigns for A2P messaging
 * - RCS: Rich Communication Services campaigns
 */
export const CampaignEnum = {
    TollFree: "TOLL_FREE",
    TenDlc: "10DLC",
    Rcs: "RCS",
} as const;
export type CampaignEnum = (typeof CampaignEnum)[keyof typeof CampaignEnum];
