/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../index.js";

/**
 * Information about the campaign associated with a conversation
 */
export interface CampaignQuery {
    /** Unique identifier for the campaign */
    id: string;
    type: Pinnacle.CampaignEnum;
}
