/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Height of the media in the card. Only available for vertical cards.
 */
export type CardStyleMediaHeight = "medium" | "small" | "tall";

export const CardStyleMediaHeight = {
    Medium: "medium",
    Small: "small",
    Tall: "tall",
} as const;
