/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CardStylePayloadWidth = "small" | "medium";

export const CardStylePayloadWidth = {
    Small: "small",
    Medium: "medium",
} as const;
