/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../index";

export interface Card {
    /** The title of the card. */
    title: string;
    /** Optional subtitle for the card. */
    subtitle?: string;
    /** Optional media URL displayed with the card. */
    mediaUrl?: string;
    /** Optional list of buttons on the card (max 4). */
    buttons?: Pinnacle.Action[];
}
