/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Industry your business operates in.
 */
export type CompanySectorReq =
    | "AGRICULTURE"
    | "COMMUNICATION"
    | "CONSTRUCTION"
    | "EDUCATION"
    | "ENERGY"
    | "ENTERTAINMENT"
    | "FINANCIAL"
    | "GAMBLING"
    | "GOVERNMENT"
    | "HEALTHCARE"
    | "HOSPITALITY"
    | "INSURANCE"
    | "MANUFACTURING"
    | "NGO"
    | "REAL_ESTATE"
    | "RETAIL"
    | "TECHNOLOGY";
export const CompanySectorReq = {
    Agriculture: "AGRICULTURE",
    Communication: "COMMUNICATION",
    Construction: "CONSTRUCTION",
    Education: "EDUCATION",
    Energy: "ENERGY",
    Entertainment: "ENTERTAINMENT",
    Financial: "FINANCIAL",
    Gambling: "GAMBLING",
    Government: "GOVERNMENT",
    Healthcare: "HEALTHCARE",
    Hospitality: "HOSPITALITY",
    Insurance: "INSURANCE",
    Manufacturing: "MANUFACTURING",
    Ngo: "NGO",
    RealEstate: "REAL_ESTATE",
    Retail: "RETAIL",
    Technology: "TECHNOLOGY",
} as const;
