// This file was auto-generated by Fern from our API Definition.

export interface ContactId {
    /** Unique ID of the created contact. This identifier is a string that always begins with the prefix `co_`, for example: `co_1234567890`. */
    id: string;
}
