// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../index.js";

/**
 * Collection of contact profiles associated with a phone number.
 * May include multiple profiles if the number is associated with different online identities.
 */
export type EnhancedContact = Pinnacle.EnhancedContactItem[];
