// This file was auto-generated by Fern from our API Definition.

/**
 * Standard error response returned when a request cannot be processed successfully.
 */
export interface Error_ {
    /** Human-readable description of the error that occurred, corresponding to the HTTP status code. */
    error: string;
}
