// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../index.js";

export interface ExtendedRcsCampaign {
    /** Agent configured to the campaign. */
    agent: ExtendedRcsCampaign.Agent;
    /** Agent's unique identifier. */
    agentId: string;
    /** Brand associated with this campaign. */
    brand: Pinnacle.ExtendedBrand;
    /** Unique identifier for the campaign. This identifier is a string that always begins with the prefix `rcs_`, for example: `rcs_1234567890`. */
    campaignId?: string;
    /** List of what the agent might say to users. */
    expectedAgentResponses?: string[];
    /** Legal documentation links. */
    links?: ExtendedRcsCampaign.Links;
    status: Pinnacle.ProfileStatusEnum;
    /** Use case classification for the campaign. */
    useCase?: ExtendedRcsCampaign.UseCase;
    /** Details on how opt-in is acquired. If it is done through a website or app, provide the link. */
    optInTermsAndConditions?: string;
    messagingType?: Pinnacle.RcsMessagingTypeEnum;
    /** Description of the agent's purpose, shown to carriers for approval. */
    carrierDescription?: string;
    keywords?: ExtendedRcsCampaign.Keywords;
    traffic?: ExtendedRcsCampaign.Traffic;
    /** Explanation of how the agent is triggered. This includes how the first message is delivered, whether messages follow a schedule or triggered by user actions, and any external triggers. */
    agentTriggers?: string;
    /** Description of all agent interactions. */
    interactionDescription?: string;
    /** Whether the agent supports conversational flows or respond to P2A messages from the users. Set to false for one-way messages from agent to user. */
    isConversational?: boolean;
    /**
     * Required text that appears next to the opt-in checkbox for your opt-in form. This checkbox has to be unchecked by default. The text should meet the US CTIA requirements and is usually in the following format: <br>
     *
     * [Program description of the company sending the messages and what type of messages are being sent]. Msg&data rates may apply. [Message frequency: How frequently messages are sent]. [Privacy statement or link to privacy policy]. [Link to full mobile
     * T&Cs page].
     */
    ctaLanguage?: string;
    /** Instructions on how an external reviewer can trigger messages and an example flow from the agent. This is usually an inbound text message to the agent that will start a flow of messages between the agent and the user. */
    demoTrigger?: string;
}

export namespace ExtendedRcsCampaign {
    /**
     * Agent configured to the campaign.
     */
    export interface Agent {
        /** Color of the agent's buttons. */
        color?: string;
        /** Description of the agent. */
        description?: string;
        /** List of emails. */
        emails: Agent.Emails.Item[];
        /** Link to the agent's hero. Hero must be an image file with dimensions 1440x448px. */
        heroUrl?: string;
        /** Link to the agent's icon. Icon must be an image file with dimensions 224x224px. */
        iconUrl?: string;
        /** Name of the agent. */
        name?: string;
        /** List of phone numbers. */
        phones: Agent.Phones.Item[];
        /** List of urls. */
        websites: Agent.Websites.Item[];
    }

    export namespace Agent {
        export type Emails = Emails.Item[];

        export namespace Emails {
            export interface Item {
                /** Email attached to the agent. */
                email?: string;
                /** Label for the email. */
                label?: string;
            }
        }

        export type Phones = Phones.Item[];

        export namespace Phones {
            export interface Item {
                /** Label for the phone number. */
                label?: string;
                /** Phone number attached to the agent in E.164 format. */
                phone?: string;
            }
        }

        export type Websites = Websites.Item[];

        export namespace Websites {
            export interface Item {
                /** Label for the url. */
                label?: string;
                /** Url attached to the agent. */
                url?: string;
            }
        }
    }

    /**
     * Legal documentation links.
     */
    export interface Links {
        /** Privacy policy URL. */
        privacyPolicy?: string;
        /** Terms of service URL. */
        termsOfService?: string;
    }

    /**
     * Use case classification for the campaign.
     */
    export interface UseCase {
        /** Detailed summary of what the brand is and how this agent will be used. */
        behavior?: string;
        value?: Pinnacle.RcsCampaignUseCaseEnum;
    }

    export interface Keywords {
        HELP?: Keywords.Help;
        OPT_IN?: Keywords.OptIn;
        OPT_OUT?: Keywords.OptOut;
    }

    export namespace Keywords {
        export interface Help {
            /** Message sent when a user sends HELP. Must include at least one support contact method (phone, email, or website). */
            message?: string;
            /** Keywords that trigger help response. */
            keywords?: string[];
        }

        export interface OptIn {
            /** Message sent when a user opt-in. Must include brand name, confirmation of subscription, and disclosures (STOP and HELP instructions, message and data rates). */
            message?: string;
            /** Keywords that trigger opt-in response. */
            keywords?: string[];
        }

        export interface OptOut {
            /** Message sent when a user opt-out. Must include brand name, acknowledge opt-out request and state user will not receive further messages. No marketing or re-engagement attempts. */
            message?: string;
            /** Keywords that trigger opt-out response. */
            keywords?: string[];
        }
    }

    export interface Traffic {
        /** Estimated monthly website visitors. */
        monthlyWebsite?: number;
        /** Estimated monthly RCS messages sent. */
        monthlyRcsEstimate?: number;
    }
}
