// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../index.js";

export interface ExtendedRcsCampaign {
    /** Agent configured to the campaign. */
    agent: ExtendedRcsCampaign.Agent;
    /** Agent's unique identifier. */
    agentId: string;
    /** Brand associated with this campaign. */
    brand: Pinnacle.ExtendedBrand;
    /** Unique identifier for the campaign. This identifier is a string that always begins with the prefix `rcs_`, for example: `rcs_1234567890`. */
    campaignId?: string;
    /** List of what the agent might say to users. See the [Expected Agent Responses](/guides/campaigns/rcs-compliance#expected-agent-responses) section for requirements. */
    expectedAgentResponses?: string[];
    /** Legal documentation links. */
    links?: ExtendedRcsCampaign.Links;
    status: Pinnacle.ProfileStatusEnum;
    /** Detailed summary of what the brand is and how this agent will be used. See the [Use Case Behavior](/guides/campaigns/rcs-compliance#use-case-behavior) section for requirements. */
    useCaseDescription?: string;
    messagingType?: Pinnacle.RcsMessagingTypeEnum;
    /** URL to the opt-in form or a URL to a screenshot of the opt-in CTA. */
    ctaMedia?: string;
    /** Details on how opt-in is acquired. If it is done through a website or app, provide the link. See the [Opt-In Method](/guides/campaigns/rcs-compliance#opt-in-method) section for requirements. */
    optInMethod?: string;
    keywords?: ExtendedRcsCampaign.Keywords;
    traffic?: ExtendedRcsCampaign.Traffic;
    /** Required text that appears next to the opt-in checkbox for your opt-in form. This checkbox has to be unchecked by default. See the [CTA Language](/guides/campaigns/rcs-compliance#cta-language-opt-in-disclosure) section for requirements. */
    ctaLanguage?: string;
    /** Instructions on how an external reviewer can trigger messages and an example flow from the agent. This is usually an inbound text message to the agent that will start a flow of messages between the agent and the user. See the [Demo Trigger](/guides/campaigns/rcs-compliance#demo-trigger) section for requirements. */
    demoTrigger?: string;
}

export namespace ExtendedRcsCampaign {
    /**
     * Agent configured to the campaign.
     */
    export interface Agent {
        /** Color of the agent's buttons. */
        color?: string;
        /** Description of the agent. */
        description?: string;
        /** List of emails. */
        emails: Agent.Emails.Item[];
        /** Link to the agent's hero. Hero must be an image file with dimensions 1440x448px. */
        heroUrl?: string;
        /** Link to the agent's icon. Icon must be an image file with dimensions 224x224px. */
        iconUrl?: string;
        /** Name of the agent. */
        name?: string;
        /** List of phone numbers. */
        phones: Agent.Phones.Item[];
        /** List of urls. */
        websites: Agent.Websites.Item[];
    }

    export namespace Agent {
        export type Emails = Emails.Item[];

        export namespace Emails {
            export interface Item {
                /** Email attached to the agent. */
                email?: string;
                /** Label for the email. */
                label?: string;
            }
        }

        export type Phones = Phones.Item[];

        export namespace Phones {
            export interface Item {
                /** Label for the phone number. */
                label?: string;
                /** Phone number attached to the agent in E.164 format. */
                phone?: string;
            }
        }

        export type Websites = Websites.Item[];

        export namespace Websites {
            export interface Item {
                /** Label for the url. */
                label?: string;
                /** Url attached to the agent. */
                url?: string;
            }
        }
    }

    /**
     * Legal documentation links.
     */
    export interface Links {
        /** Privacy policy URL. */
        privacyPolicy?: string;
        /** Terms of service URL. */
        termsOfService?: string;
    }

    export interface Keywords {
        HELP?: Keywords.Help;
        OPT_IN?: Keywords.OptIn;
        OPT_OUT?: Keywords.OptOut;
    }

    export namespace Keywords {
        export interface Help {
            /** Message sent when a user sends HELP. Must include at least one support contact method (phone, email, or website). See the [Keyword Response Messages](/guides/campaigns/rcs-compliance#keyword-response-messages) section for requirements. */
            message?: string;
            /** Keywords that trigger help response. */
            keywords?: string[];
        }

        export interface OptIn {
            /** Message sent when a user opts in. Must include brand name, confirmation of subscription, and disclosures (STOP and HELP instructions, message and data rates). See the [Keyword Response Messages](/guides/campaigns/rcs-compliance#keyword-response-messages) section for requirements. */
            message?: string;
            /** Keywords that trigger opt-in response. */
            keywords?: string[];
        }

        export interface OptOut {
            /** Message sent when a user opts out. Must include brand name, acknowledge opt-out request and state user will not receive further messages. No marketing or re-engagement attempts. See the [Keyword Response Messages](/guides/campaigns/rcs-compliance#keyword-response-messages) section for requirements. */
            message?: string;
            /** Keywords that trigger opt-out response. */
            keywords?: string[];
        }
    }

    export interface Traffic {
        /** Estimated monthly website visitors. */
        monthlyWebsite?: number;
        /** Estimated monthly RCS messages sent. */
        monthlyRcsEstimate?: number;
    }
}
