// This file was auto-generated by Fern from our API Definition.

/**
 * Subtle repeating SVG pattern tinted by the palette's foreground color.
 */
export interface FormBackgroundPattern {
    /** Which built-in pattern to render. */
    preset: FormBackgroundPattern.Preset;
}

export namespace FormBackgroundPattern {
    /** Which built-in pattern to render. */
    export const Preset = {
        Noise: "noise",
        Dots: "dots",
        Mesh: "mesh",
        Grid: "grid",
        Waves: "waves",
        Topo: "topo",
    } as const;
    export type Preset = (typeof Preset)[keyof typeof Preset];
}
