// This file was auto-generated by Fern from our API Definition.

/**
 * Per-mode palette. All three colors are optional; any you omit fall back to the team default for that mode.
 */
export interface FormColorPalette {
    /** Accent color used for the submit button, focus rings, filled checkboxes, and other interactive surfaces. */
    primary?: string;
    /** Page background color. Fallback solid color used by Safari chrome tinting and safe-area regions. */
    background?: string;
    /** Body text and label color. */
    text?: string;
}
