// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../index.js";

export interface HostedSilentAuthResponse {
    requestId: Pinnacle.NetworkRequestId;
    /** URL to open on the user's cellular device when Pinnacle should handle the browser/WebView flow. */
    browserUrl: string;
    /** Expiration timestamp for the initial Silent Auth device handoff. Silent Auth URLs expire 60 seconds after creation and should be opened immediately from the user's cellular device. */
    expiresAt: string;
}
