/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../index.js";

export interface InboundMessage {
    from: string;
    to: string;
    messageType: InboundMessage.MessageType;
    metadata?: InboundMessage.Metadata;
}

export namespace InboundMessage {
    export type MessageType = "text" | "media" | "action" | "location";
    export const MessageType = {
        Text: "text",
        Media: "media",
        Action: "action",
        Location: "location",
    } as const;

    export interface Metadata {
        sender?: Pinnacle.SenderMetadata;
        message?: Pinnacle.MessageMetadata;
    }
}
