// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../index.js";

export interface ListRcsCampaignsResponse {
    data: Pinnacle.RcsCampaignSummary[];
    hasMore: boolean;
    count: number;
}
