// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../index.js";

export interface ListPhoneNumbersResponse {
    data: Pinnacle.OwnedPhoneNumber[];
    hasMore: boolean;
    count: number;
}
