// This file was auto-generated by Fern from our API Definition.

/** Current status of the message. */
export const MessageStatusEnum = {
    Queued: "QUEUED",
    Pending: "PENDING",
    Sent: "SENT",
    SendFailed: "SEND_FAILED",
    Delivered: "DELIVERED",
    DeliveryFailed: "DELIVERY_FAILED",
    Received: "RECEIVED",
    Read: "READ",
} as const;
export type MessageStatusEnum = (typeof MessageStatusEnum)[keyof typeof MessageStatusEnum];
