/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../index.js";

export interface Message {
    content: Pinnacle.MessageContentType;
    /**
     * Total cost charged for sending the message. <br>
     *
     * Null means the message incurred no cost or has not been charged yet.
     */
    cost?: number | null;
    /**
     * Timestamp indicating when the message was successfully delivered to the recipient. <br>
     *
     * Null indicates the message has not yet been delivered.
     */
    deliveredAt?: string | null;
    /**
     * Detailed explanation of any errors that occurred while delivering the message. <br>
     *
     * Null indicates no errors.
     */
    error?: string | null;
    /** Unique identifier of the message. */
    id: number;
    method: Pinnacle.MessageMethod;
    /** Number of segments the message was split into for delivery. */
    numSegments: number;
    /** Phone number that received the message in E.164 format. */
    receiver: string;
    /** Phone number or agent that sent the message. */
    sender: string;
    /**
     * Timestamp indicating when the message was submitted for delivery. <br>
     *
     * Null indicates the message is still in the queue.
     */
    sentAt?: string | null;
    status: Pinnacle.MessageStatus;
    type: Pinnacle.MessageType;
}
