// This file was auto-generated by Fern from our API Definition.

/** Availability of the carrier-backed insight. */
export const NetworkInsightStatus = {
    Available: "available",
    Unavailable: "unavailable",
    Unsupported: "unsupported",
    Failed: "failed",
} as const;
export type NetworkInsightStatus = (typeof NetworkInsightStatus)[keyof typeof NetworkInsightStatus];
