/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../index.js";

/**
 * Configure how your RCS message is sent and tracked.
 */
export interface Options {
    schedule?: Pinnacle.MessageSchedule;
    /** Send via the test agent to whitelisted test devices. Useful for development and debugging. */
    test_mode?: boolean;
    tracking?: Pinnacle.Tracking;
    /** Media files and card media will be transcoded to a supported RCS format. This adds a small delay to sending the message. Ignored for rich text messages. */
    transcode?: boolean;
    /**
     * Validate your message for any unsupported files. <br>
     *
     * If failed, errors will be thrown and the message will not send.
     */
    validate?: boolean;
}
