/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../index.js";

/**
 * Details of a phone number available for purchase.
 * Includes all essential data required for acquisition and operational planning.
 */
export interface PhoneNumber {
    /** Phone number in E.164 format. */
    number: string;
    /** Classification that defines the number's billing model and geographic scope. */
    phone_type: Pinnacle.PhoneTypesSchema;
    /** Pricing details for the phone number. */
    cost: PhoneNumber.Cost;
    /** Supported communication capabilities associated with the number. */
    features: Pinnacle.PhoneFeatures[];
    /** Geographic and routing information for the phone number. */
    region: PhoneNumber.Region;
}

export namespace PhoneNumber {
    /**
     * Pricing details for the phone number.
     */
    export interface Cost {
        /** Recurring monthly fee covering number ownership and basic services. */
        monthly: number;
        /** One-time activation or setup fee charged at purchase. */
        upfront: number;
        /** Three-letter currency code for all pricing values. */
        currency: string;
    }

    /**
     * Geographic and routing information for the phone number.
     */
    export interface Region {
        /** Two-letter country code where the number is registered. */
        country: string;
        /** State or province code applicable to local numbers. */
        state?: string;
        /** Primary city or metropolitan area served by the number. */
        city?: string;
        /**
         * Telecommunications rate center used for call routing and billing,
         * defining local calling area boundaries.
         */
        rateCenter?: string;
    }
}
