/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../index.js";

export interface PinnacleUrlWithClicks extends Pinnacle.PinnacleUrl {
    /**
     * Array of click analytics data for this URL. <br>
     *
     * Click data will be empty if no one has visited your link yet.
     */
    clicks: Pinnacle.LinkClickEvent[];
}
