// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../index.js";

/**
 * Single-select radio group.
 */
export interface RadioField extends Pinnacle.FieldBase {
    /** Choices shown as radio buttons. At least one is required. */
    options: Pinnacle.FormFieldOption[];
}
