/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../index.js";

/**
 * Button that opens a URL when tapped by the recipient.
 */
export interface RcsButtonOpenUrl {
    /** The URL to open when the button is tapped. Must be a valid HTTP or HTTPS URL. */
    payload: string;
    title: Pinnacle.RcsButtonTitleSchema;
}
