// This file was auto-generated by Fern from our API Definition.

/** Opt in options. */
export const RcsCampaignOptInMethodEnum = {
    Website: "WEBSITE",
    Sms: "SMS",
    App: "APP",
    Verbal: "VERBAL",
    Written: "WRITTEN",
    Other: "OTHER",
} as const;
export type RcsCampaignOptInMethodEnum = (typeof RcsCampaignOptInMethodEnum)[keyof typeof RcsCampaignOptInMethodEnum];
