/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Metadata about the media file in the message.
 */
export interface RcsMediaDetailsContent {
    /** Path to the file in Pinnacle's storage. */
    fullPath?: string;
    /** Detected MIME type of the media file. */
    mimeType: string;
    /** Direct URL to the media file. */
    url: string;
}
