/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../index.js";

export type RcsValidateContent =
    /**
     * Message containing longer text content with optional quick reply buttons. */
    | Pinnacle.RcsTextContent
    /**
     * Message containing a media file and/or text with optional quick reply buttons.<br>
     *
     * See [supported media types](https://app.pinnacle.sh/supported-file-types?type=RCS-MEDIA). */
    | {
          media: string;
          quickReplies: Pinnacle.RichButton[];
      }
    /**
     * Message containing cards, each with its own title, subtitle, and/or buttons. Quick replies can also be added. <br>
     *
     * See [supported file types](https://app.pinnacle.sh/supported-file-types?type=RCS-CARD). */
    | Pinnacle.RcsCards;
