// This file was auto-generated by Fern from our API Definition.

export interface ReactionResult {
    /** Unique identifier of the message. This identifier is a string that always begins with the prefix `msg_`, for example: `msg_1234567890`. */
    messageId: string;
    /** Unique identifier of the message with the reaction. This identifier is a string that always begins with the prefix `msg_`, for example: `msg_1234567890`. */
    reactionMessageId: string;
}
