// This file was auto-generated by Fern from our API Definition.

/**
 * Response returned when a blast is scheduled for future delivery.
 */
export interface ScheduledBlastDetails {
    /** Unique identifier for the scheduled blast. This identifier is a string that always begins with the prefix `msg_sched_`, for example: `msg_sched_xxxxx`. */
    scheduleId: string;
    /** The schedule configuration for the blast. */
    config: ScheduledBlastDetails.Config;
}

export namespace ScheduledBlastDetails {
    /**
     * The schedule configuration for the blast.
     */
    export interface Config {
        /** When the first message will be sent. */
        sendAt?: string;
        /** AWS cron expression for recurring schedules. */
        recurrence?: string;
        /** IANA timezone identifier. */
        timezone?: string;
        /** When recurring schedules will stop. */
        endDate?: string;
    }
}
