// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../index.js";

/**
 * Send a form from a phone number. `from` must be an E.164 phone.
 */
export interface SendFormViaSmsParams {
    /** Sender phone in E.164. */
    from: string;
    /** Recipient phone in E.164. Omit to mint a URL-only form without sending a message. */
    to?: string;
    form: SendFormViaSmsParams.Form;
    options?: Pinnacle.SendFormOptions;
}

export namespace SendFormViaSmsParams {
    export type Form = Pinnacle.FormIdReference | Pinnacle.FormDefinition;
}
