/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ShareLocation {
    /** The title for the share location action. Maximum length is 25 characters. */
    title: string;
    /** The type of action being sent */
    actionType: "share_location";
}
