// This file was auto-generated by Fern from our API Definition.

export interface ShortenedUrl {
    /** Your custom shortened link following the format `https://pncl.to/{linkId}`, where `{linkId}` is the unique identifier for the URL that can be used with our other endpoint. */
    url: string;
    config: ShortenedUrl.Config;
}

export namespace ShortenedUrl {
    export interface Config {
        /** Destination URL that your shortened link redirects to. */
        to: string;
        /** Expiration date for your shortened link in ISO 8601 format, or null if it's permanent. */
        expiresAt: string | null;
    }
}
