// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../index.js";

/**
 * Simulate a button press from a user.
 */
export interface SimulateUserButton {
    /** User phone number in E.164 format. */
    from: string;
    /** RCS agent ID (prefixed with `agent_`). */
    to: string;
    button: Pinnacle.UserButtonPress;
}
