/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../index";

export interface SmsMessage {
    /** The recipient's phone number */
    phoneNumber: string;
    /** The type of message being sent */
    messageType: "sms";
    /** The content of the message */
    message: Pinnacle.SmsMessageMessage;
}
