/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Classification of the phone number type based on Telesign’s taxonomy.
 * Indicates the phone’s service category, such as mobile, fixed line, toll-free, or VOIP,
 * along with special types like prepaid, pager, or restricted premium.
 * The "INVALID" type denotes an unrecognized or improperly formatted number.
 */
export type TelesignPhoneType =
    | "FIXED_LINE"
    | "MOBILE"
    | "PREPAID"
    | "TOLL_FREE"
    | "VOIP"
    | "PAGER"
    | "PAYPHONE"
    | "INVALID"
    | "RESTRICTED_PREMIUM"
    | "PERSONAL"
    | "VOICEMAIL"
    | "OTHER";
export const TelesignPhoneType = {
    FixedLine: "FIXED_LINE",
    Mobile: "MOBILE",
    Prepaid: "PREPAID",
    TollFree: "TOLL_FREE",
    Voip: "VOIP",
    Pager: "PAGER",
    Payphone: "PAYPHONE",
    Invalid: "INVALID",
    RestrictedPremium: "RESTRICTED_PREMIUM",
    Personal: "PERSONAL",
    Voicemail: "VOICEMAIL",
    Other: "OTHER",
} as const;
