/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UploadResults {
    /** Presigned URL for uploading your file to storage. */
    uploadUrl: string;
    /** Presigned URL for downloading your file. */
    downloadUrl: string;
    metadata: UploadResults.Metadata;
}

export namespace UploadResults {
    export interface Metadata {
        /** Name of the uploaded file. */
        fileName: string;
        /** MIME type of the file. */
        contentType: string;
        /**
         * Expiration date in ISO 8601 format for file download access.<br>
         *
         * Null indicates that `download.expiresAt` was not provided and the expiration time is defaulted to one hour after uploading.
         */
        expiresAt: string | null;
    }
}
