// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../index.js";

/**
 * URL input. Server requires a valid absolute URL.
 */
export interface UrlField extends Pinnacle.FieldBase {
    /** Ghost text shown inside the input while it's empty. */
    placeholder?: string;
}
