// This file was auto-generated by Fern from our API Definition.

/**
 * Simulates when a user presses a `requestUserLocation` button.
 */
export interface UserButtonPressRequestUserLocation {
    /** Name of the button that you want to press. */
    title: string;
    /** Metadata attached to the button. */
    metadata?: string;
    /** Location the simulated user responded with. */
    location?: UserButtonPressRequestUserLocation.Location;
}

export namespace UserButtonPressRequestUserLocation {
    /**
     * Location the simulated user responded with.
     */
    export interface Location {
        text?: string;
        latitude?: number;
        longitude?: number;
        address?: string;
    }
}
