// This file was auto-generated by Fern from our API Definition.

export interface WebhookSummary {
    /** Unique identifier of the webhook. This identifier is a string that always begins with the prefix `wh_`, for example: `wh_1234567890`. */
    id: string;
    /** Name of the webhook. */
    name: string;
    /** URL where webhook events are delivered. */
    endpoint: string;
    /** Current status of the webhook. */
    status: WebhookSummary.Status;
    /** ISO 8601 timestamp of when the webhook was created. */
    createdAt: string;
    /** ISO 8601 timestamp of when the webhook was last updated. */
    updatedAt: string;
    /** Optional custom HTTP headers sent when dispatching webhook events. Header names must match the regex `^[A-Za-z0-9][A-Za-z0-9_-]*$` — start with a letter or digit and contain only letters, digits, `-`, or `_`. Keys are case-insensitive and stored in uppercase. Values must be strings. The reserved `PINNACLE-SIGNING-SECRET` header is never returned here and cannot be overridden. */
    headers?: Record<string, string | null> | null;
}

export namespace WebhookSummary {
    /** Current status of the webhook. */
    export const Status = {
        Disabled: "DISABLED",
        Enabled: "ENABLED",
        Deleted: "DELETED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
