// This file was auto-generated by Fern from our API Definition.

export interface ZodError {
    /** Human-readable summary of validation failures. */
    description: string;
    /**
     * Structured dictionary of issues containing two main sections:
     * - `errors`: Array of global validation errors not tied to specific fields
     * - `properties`: Object mapping field names to their specific validation errors, where each field contains an `errors` array
     */
    errors: Record<string, unknown>;
    /** Accepts any additional properties */
    [key: string]: any;
}
