/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool";
import { PinnacleClient } from "../../../src/Client";
import * as Pinnacle from "../../../src/api/index";

describe("Rcs", () => {
    test("autofill (6efd3c99)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            additionalInfo: "Please autofill missing DLC campaign fields using my brand profile",
            campaignId: 161,
        };
        const rawResponseBody = {
            agent: {
                name: "Pinnacle Software Development",
                description:
                    "Engaging campaigns with RBM – next-gen SMS marketing with rich content and better analytics.",
                color: "#000000",
                emails: [{ email: "founders@trypinnacle.app", label: "Email Us" }],
                phones: [{ phone: "+14154467821", label: "Contact us directly" }],
                websites: [{ url: "https://www.trypinnacle.app/", label: "Get started with Pinnacle" }],
                heroUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9mmw7kfynqiKSPfsaoc6",
                iconUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9gvlDunZEw1krfruZmw3",
            },
            campaignId: 161,
            expectedAgentResponses: [
                "Here are the things I can help you with.",
                "I can assist you with booking an appointment, or you may choose to book manually.",
                "Here are the available times to connect with a representative tomorrow.",
                "Your appointment has been scheduled.",
            ],
            links: {
                privacyPolicy: "https://www.trypinnacle.app/privacy",
                termsOfService: "https://www.trypinnacle.app/terms",
            },
            optIn: { termsAndConditions: "Would you like to subscribe to Pinnacle?", method: "WEBSITE" },
            optOut: { description: "Reply STOP to opt-out anytime.", keywords: ["STOP", "UNSUBSCRIBE", "END"] },
            useCase: { behavior: "Acts as a customer service representative.", value: "OTHER" },
            brand: 2,
        };
        server
            .mockEndpoint()
            .post("/campaigns/rcs/autofill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.rcs.autofill({
            additionalInfo: "Please autofill missing DLC campaign fields using my brand profile",
            campaignId: 161,
        });
        expect(response).toEqual({
            agent: {
                name: "Pinnacle Software Development",
                description:
                    "Engaging campaigns with RBM \u2013 next-gen SMS marketing with rich content and better analytics.",
                color: "#000000",
                emails: [
                    {
                        email: "founders@trypinnacle.app",
                        label: "Email Us",
                    },
                ],
                phones: [
                    {
                        phone: "+14154467821",
                        label: "Contact us directly",
                    },
                ],
                websites: [
                    {
                        url: "https://www.trypinnacle.app/",
                        label: "Get started with Pinnacle",
                    },
                ],
                heroUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9mmw7kfynqiKSPfsaoc6",
                iconUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9gvlDunZEw1krfruZmw3",
            },
            campaignId: 161,
            expectedAgentResponses: [
                "Here are the things I can help you with.",
                "I can assist you with booking an appointment, or you may choose to book manually.",
                "Here are the available times to connect with a representative tomorrow.",
                "Your appointment has been scheduled.",
            ],
            links: {
                privacyPolicy: "https://www.trypinnacle.app/privacy",
                termsOfService: "https://www.trypinnacle.app/terms",
            },
            optIn: {
                termsAndConditions: "Would you like to subscribe to Pinnacle?",
                method: "WEBSITE",
            },
            optOut: {
                description: "Reply STOP to opt-out anytime.",
                keywords: ["STOP", "UNSUBSCRIBE", "END"],
            },
            useCase: {
                behavior: "Acts as a customer service representative.",
                value: "OTHER",
            },
            brand: 2,
        });
    });

    test("autofill (c69805ed)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { additionalInfo: undefined, campaignId: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs/autofill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.autofill({
                additionalInfo: undefined,
                campaignId: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.BadRequestError({
                key: "value",
            }),
        );
    });

    test("autofill (b8de75ad)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { additionalInfo: undefined, campaignId: undefined };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs/autofill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.autofill({
                additionalInfo: undefined,
                campaignId: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.UnauthorizedError({
                error: "error",
            }),
        );
    });

    test("autofill (12942199)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { additionalInfo: undefined, campaignId: undefined };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs/autofill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.autofill({
                additionalInfo: undefined,
                campaignId: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.InternalServerError({
                error: "error",
            }),
        );
    });

    test("get (7139be34)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            agent: {
                color: "#000000",
                description:
                    "Engaging campaigns with RBM – next-gen SMS marketing with rich content and better analytics.",
                emails: [{ email: "founders@trypinnacle.app", label: "Email Us" }],
                heroUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9mmw7kfynqiKSPfsaoc6",
                iconUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9gvlDunZEw1krfruZmw3",
                name: "Pinnacle Software Development",
                phones: [{ label: "Contact us directly", phone: "+14154467821" }],
                websites: [{ label: "Get started with Pinnacle", url: "https://www.trypinnacle.app/" }],
            },
            agentId: "agent_V1StGXR8_Z5j",
            brand: {
                address: "500 Folsom Street, San Francisco, CA 94105",
                contact: {
                    email: "janedoe1@pinnacle.example",
                    name: "Jane Doe",
                    phone: "+14155550123",
                    title: "Customer Support Specialist",
                },
                dba: "Pinnacle RCS",
                description: "description",
                ein: "12-3456789",
                email: "founders@trypinnacle.app",
                name: "Pinnacle",
                sector: "TECHNOLOGY",
                type: "PRIVATE_PROFIT",
                website: "https://www.pinnacle.sh/",
                createdAt: "2024-08-17T08:00:30.632",
                id: 2,
                isArchived: false,
                status: "VERIFIED",
                updatedAt: "2024-12-09T10:03:54.934",
            },
            brandAttestation: true,
            campaignId: 161,
            expectedAgentResponses: [
                "Here are the things I can help you with.",
                "I can assist you with booking an appointment, or you may choose to book manually.",
                "Here are the available times to connect with a representative tomorrow.",
                "Your appointment has been scheduled.",
            ],
            links: {
                privacyPolicy: "https://www.trypinnacle.app/privacy",
                termsOfService: "https://www.trypinnacle.app/terms",
            },
            optIn: { method: "WEBSITE", termsAndConditions: "Would you like to subscribe to Pinnacle?" },
            optOut: { description: "Reply STOP to opt-out anytime.", keywords: ["STOP", "UNSUBSCRIBE", "END"] },
            useCase: { behavior: "Acts as a customer service representative.", value: "OTHER" },
        };
        server.mockEndpoint().get("/campaigns/rcs/161").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.campaigns.rcs.get(161);
        expect(response).toEqual({
            agent: {
                color: "#000000",
                description:
                    "Engaging campaigns with RBM \u2013 next-gen SMS marketing with rich content and better analytics.",
                emails: [
                    {
                        email: "founders@trypinnacle.app",
                        label: "Email Us",
                    },
                ],
                heroUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9mmw7kfynqiKSPfsaoc6",
                iconUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9gvlDunZEw1krfruZmw3",
                name: "Pinnacle Software Development",
                phones: [
                    {
                        label: "Contact us directly",
                        phone: "+14154467821",
                    },
                ],
                websites: [
                    {
                        label: "Get started with Pinnacle",
                        url: "https://www.trypinnacle.app/",
                    },
                ],
            },
            agentId: "agent_V1StGXR8_Z5j",
            brand: {
                address: "500 Folsom Street, San Francisco, CA 94105",
                contact: {
                    email: "janedoe1@pinnacle.example",
                    name: "Jane Doe",
                    phone: "+14155550123",
                    title: "Customer Support Specialist",
                },
                dba: "Pinnacle RCS",
                description: "description",
                ein: "12-3456789",
                email: "founders@trypinnacle.app",
                name: "Pinnacle",
                sector: "TECHNOLOGY",
                type: "PRIVATE_PROFIT",
                website: "https://www.pinnacle.sh/",
                createdAt: "2024-08-17T08:00:30.632",
                id: 2,
                isArchived: false,
                status: "VERIFIED",
                updatedAt: "2024-12-09T10:03:54.934",
            },
            brandAttestation: true,
            campaignId: 161,
            expectedAgentResponses: [
                "Here are the things I can help you with.",
                "I can assist you with booking an appointment, or you may choose to book manually.",
                "Here are the available times to connect with a representative tomorrow.",
                "Your appointment has been scheduled.",
            ],
            links: {
                privacyPolicy: "https://www.trypinnacle.app/privacy",
                termsOfService: "https://www.trypinnacle.app/terms",
            },
            optIn: {
                method: "WEBSITE",
                termsAndConditions: "Would you like to subscribe to Pinnacle?",
            },
            optOut: {
                description: "Reply STOP to opt-out anytime.",
                keywords: ["STOP", "UNSUBSCRIBE", "END"],
            },
            useCase: {
                behavior: "Acts as a customer service representative.",
                value: "OTHER",
            },
        });
    });

    test("get (42189d2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/campaigns/rcs/1").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.campaigns.rcs.get(1);
        }).rejects.toThrow(
            new Pinnacle.BadRequestError({
                key: "value",
            }),
        );
    });

    test("get (2ded2fac)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/campaigns/rcs/1").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.campaigns.rcs.get(1);
        }).rejects.toThrow(
            new Pinnacle.UnauthorizedError({
                error: "error",
            }),
        );
    });

    test("get (dc858a68)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/campaigns/rcs/1").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.campaigns.rcs.get(1);
        }).rejects.toThrow(
            new Pinnacle.NotFoundError({
                error: "error",
            }),
        );
    });

    test("get (cea8d60)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/campaigns/rcs/1").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.campaigns.rcs.get(1);
        }).rejects.toThrow(
            new Pinnacle.InternalServerError({
                error: "error",
            }),
        );
    });

    test("submit (3c06af76)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };
        server
            .mockEndpoint()
            .post("/campaigns/rcs/submit/161")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.rcs.submit(161);
        expect(response).toEqual({
            success: true,
        });
    });

    test("submit (42189d2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs/submit/1")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.submit(1);
        }).rejects.toThrow(
            new Pinnacle.BadRequestError({
                key: "value",
            }),
        );
    });

    test("submit (2ded2fac)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs/submit/1")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.submit(1);
        }).rejects.toThrow(
            new Pinnacle.UnauthorizedError({
                error: "error",
            }),
        );
    });

    test("submit (dc858a68)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs/submit/1")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.submit(1);
        }).rejects.toThrow(
            new Pinnacle.NotFoundError({
                error: "error",
            }),
        );
    });

    test("submit (cea8d60)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs/submit/1")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.submit(1);
        }).rejects.toThrow(
            new Pinnacle.InternalServerError({
                error: "error",
            }),
        );
    });

    test("upsert (604618e9)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            agent: {
                color: "#000000",
                description:
                    "Engaging campaigns with RBM – next-gen SMS marketing with rich content and better analytics.",
                emails: [{ email: "founders@trypinnacle.app", label: "Email Us" }],
                heroUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9mmw7kfynqiKSPfsaoc6",
                iconUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9gvlDunZEw1krfruZmw3",
                name: "Pinnacle Software Development",
                phones: [{ label: "Contact us directly", phone: "+14154467821" }],
                websites: [{ label: "Get started with Pinnacle", url: "https://www.trypinnacle.app/" }],
            },
            brand: 2,
            expectedAgentResponses: [
                "Here are the things I can help you with.",
                "I can assist you with booking an appointment, or you may choose to book manually.",
                "Here are the available times to connect with a representative tomorrow.",
                "Your appointment has been scheduled.",
            ],
            links: {
                privacyPolicy: "https://www.trypinnacle.app/privacy",
                termsOfService: "https://www.trypinnacle.app/terms",
            },
            optIn: { method: "WEBSITE", termsAndConditions: "Would you like to subscribe to Pinnacle?" },
            optOut: { description: "Reply STOP to opt-out anytime.", keywords: ["STOP", "UNSUBSCRIBE", "END"] },
            useCase: { behavior: "Acts as a customer service representative.", value: "OTHER" },
        };
        const rawResponseBody = {
            agent: {
                color: "#000000",
                description:
                    "Engaging campaigns with RBM – next-gen SMS marketing with rich content and better analytics.",
                emails: [{ email: "founders@trypinnacle.app", label: "Email Us" }],
                heroUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9mmw7kfynqiKSPfsaoc6",
                iconUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9gvlDunZEw1krfruZmw3",
                name: "Pinnacle Software Development",
                phones: [{ label: "Contact us directly", phone: "+14154467821" }],
                websites: [{ label: "Get started with Pinnacle", url: "https://www.trypinnacle.app/" }],
            },
            agentId: "agent_V1StGXR8_Z5j",
            brand: {
                address: "500 Folsom Street, San Francisco, CA 94105",
                contact: {
                    email: "janedoe1@pinnacle.example",
                    name: "Jane Doe",
                    phone: "+14155550123",
                    title: "Customer Support Specialist",
                },
                dba: "Pinnacle RCS",
                description: "description",
                ein: "12-3456789",
                email: "founders@trypinnacle.app",
                name: "Pinnacle",
                sector: "TECHNOLOGY",
                type: "PRIVATE_PROFIT",
                website: "https://www.pinnacle.sh/",
                createdAt: "2024-08-17T08:00:30.632",
                id: 2,
                isArchived: false,
                status: "VERIFIED",
                updatedAt: "2024-12-09T10:03:54.934",
            },
            brandAttestation: true,
            campaignId: 161,
            expectedAgentResponses: [
                "Here are the things I can help you with.",
                "I can assist you with booking an appointment, or you may choose to book manually.",
                "Here are the available times to connect with a representative tomorrow.",
                "Your appointment has been scheduled.",
            ],
            links: {
                privacyPolicy: "https://www.trypinnacle.app/privacy",
                termsOfService: "https://www.trypinnacle.app/terms",
            },
            optIn: { method: "WEBSITE", termsAndConditions: "Would you like to subscribe to Pinnacle?" },
            optOut: { description: "Reply STOP to opt-out anytime.", keywords: ["STOP", "UNSUBSCRIBE", "END"] },
            useCase: { behavior: "Acts as a customer service representative.", value: "OTHER" },
        };
        server
            .mockEndpoint()
            .post("/campaigns/rcs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.rcs.upsert({
            agent: {
                color: "#000000",
                description:
                    "Engaging campaigns with RBM \u2013 next-gen SMS marketing with rich content and better analytics.",
                emails: [
                    {
                        email: "founders@trypinnacle.app",
                        label: "Email Us",
                    },
                ],
                heroUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9mmw7kfynqiKSPfsaoc6",
                iconUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9gvlDunZEw1krfruZmw3",
                name: "Pinnacle Software Development",
                phones: [
                    {
                        label: "Contact us directly",
                        phone: "+14154467821",
                    },
                ],
                websites: [
                    {
                        label: "Get started with Pinnacle",
                        url: "https://www.trypinnacle.app/",
                    },
                ],
            },
            brand: 2,
            expectedAgentResponses: [
                "Here are the things I can help you with.",
                "I can assist you with booking an appointment, or you may choose to book manually.",
                "Here are the available times to connect with a representative tomorrow.",
                "Your appointment has been scheduled.",
            ],
            links: {
                privacyPolicy: "https://www.trypinnacle.app/privacy",
                termsOfService: "https://www.trypinnacle.app/terms",
            },
            optIn: {
                method: "WEBSITE",
                termsAndConditions: "Would you like to subscribe to Pinnacle?",
            },
            optOut: {
                description: "Reply STOP to opt-out anytime.",
                keywords: ["STOP", "UNSUBSCRIBE", "END"],
            },
            useCase: {
                behavior: "Acts as a customer service representative.",
                value: "OTHER",
            },
        });
        expect(response).toEqual({
            agent: {
                color: "#000000",
                description:
                    "Engaging campaigns with RBM \u2013 next-gen SMS marketing with rich content and better analytics.",
                emails: [
                    {
                        email: "founders@trypinnacle.app",
                        label: "Email Us",
                    },
                ],
                heroUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9mmw7kfynqiKSPfsaoc6",
                iconUrl: "https://agent-logos.storage.googleapis.com/_/m0bk9gvlDunZEw1krfruZmw3",
                name: "Pinnacle Software Development",
                phones: [
                    {
                        label: "Contact us directly",
                        phone: "+14154467821",
                    },
                ],
                websites: [
                    {
                        label: "Get started with Pinnacle",
                        url: "https://www.trypinnacle.app/",
                    },
                ],
            },
            agentId: "agent_V1StGXR8_Z5j",
            brand: {
                address: "500 Folsom Street, San Francisco, CA 94105",
                contact: {
                    email: "janedoe1@pinnacle.example",
                    name: "Jane Doe",
                    phone: "+14155550123",
                    title: "Customer Support Specialist",
                },
                dba: "Pinnacle RCS",
                description: "description",
                ein: "12-3456789",
                email: "founders@trypinnacle.app",
                name: "Pinnacle",
                sector: "TECHNOLOGY",
                type: "PRIVATE_PROFIT",
                website: "https://www.pinnacle.sh/",
                createdAt: "2024-08-17T08:00:30.632",
                id: 2,
                isArchived: false,
                status: "VERIFIED",
                updatedAt: "2024-12-09T10:03:54.934",
            },
            brandAttestation: true,
            campaignId: 161,
            expectedAgentResponses: [
                "Here are the things I can help you with.",
                "I can assist you with booking an appointment, or you may choose to book manually.",
                "Here are the available times to connect with a representative tomorrow.",
                "Your appointment has been scheduled.",
            ],
            links: {
                privacyPolicy: "https://www.trypinnacle.app/privacy",
                termsOfService: "https://www.trypinnacle.app/terms",
            },
            optIn: {
                method: "WEBSITE",
                termsAndConditions: "Would you like to subscribe to Pinnacle?",
            },
            optOut: {
                description: "Reply STOP to opt-out anytime.",
                keywords: ["STOP", "UNSUBSCRIBE", "END"],
            },
            useCase: {
                behavior: "Acts as a customer service representative.",
                value: "OTHER",
            },
        });
    });

    test("upsert (711f1b3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            agent: undefined,
            brand: undefined,
            campaignId: undefined,
            expectedAgentResponses: undefined,
            links: undefined,
            optIn: undefined,
            optOut: undefined,
            useCase: undefined,
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.upsert({
                agent: undefined,
                brand: undefined,
                campaignId: undefined,
                expectedAgentResponses: undefined,
                links: undefined,
                optIn: undefined,
                optOut: undefined,
                useCase: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.BadRequestError({
                key: "value",
            }),
        );
    });

    test("upsert (c4df3b3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            agent: undefined,
            brand: undefined,
            campaignId: undefined,
            expectedAgentResponses: undefined,
            links: undefined,
            optIn: undefined,
            optOut: undefined,
            useCase: undefined,
        };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.upsert({
                agent: undefined,
                brand: undefined,
                campaignId: undefined,
                expectedAgentResponses: undefined,
                links: undefined,
                optIn: undefined,
                optOut: undefined,
                useCase: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.UnauthorizedError({
                error: "error",
            }),
        );
    });

    test("upsert (fff24f4f)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            agent: undefined,
            brand: undefined,
            campaignId: undefined,
            expectedAgentResponses: undefined,
            links: undefined,
            optIn: undefined,
            optOut: undefined,
            useCase: undefined,
        };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.upsert({
                agent: undefined,
                brand: undefined,
                campaignId: undefined,
                expectedAgentResponses: undefined,
                links: undefined,
                optIn: undefined,
                optOut: undefined,
                useCase: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.NotFoundError({
                error: "error",
            }),
        );
    });

    test("upsert (8f4f3cff)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            agent: undefined,
            brand: undefined,
            campaignId: undefined,
            expectedAgentResponses: undefined,
            links: undefined,
            optIn: undefined,
            optOut: undefined,
            useCase: undefined,
        };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.upsert({
                agent: undefined,
                brand: undefined,
                campaignId: undefined,
                expectedAgentResponses: undefined,
                links: undefined,
                optIn: undefined,
                optOut: undefined,
                useCase: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.InternalServerError({
                error: "error",
            }),
        );
    });

    test("validate (4f46db2a)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            additionalInfo: "Please validate this DLC campaign for 10DLC compliance",
            campaignId: 161,
        };
        const rawResponseBody = {
            errors: [{ description: "description", example: "example", field: "field" }],
            is_valid: true,
        };
        server
            .mockEndpoint()
            .post("/campaigns/rcs/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.rcs.validate({
            additionalInfo: "Please validate this DLC campaign for 10DLC compliance",
            campaignId: 161,
        });
        expect(response).toEqual({
            errors: [
                {
                    description: "description",
                    example: "example",
                    field: "field",
                },
            ],
            is_valid: true,
        });
    });

    test("validate (fd6bfed0)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { additionalInfo: undefined, campaignId: 1 };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.validate({
                additionalInfo: undefined,
                campaignId: 1,
            });
        }).rejects.toThrow(
            new Pinnacle.BadRequestError({
                key: "value",
            }),
        );
    });

    test("validate (dd3589c2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { additionalInfo: undefined, campaignId: 1 };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.validate({
                additionalInfo: undefined,
                campaignId: 1,
            });
        }).rejects.toThrow(
            new Pinnacle.UnauthorizedError({
                error: "error",
            }),
        );
    });

    test("validate (62c2bef6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { additionalInfo: undefined, campaignId: 1 };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/rcs/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.rcs.validate({
                additionalInfo: undefined,
                campaignId: 1,
            });
        }).rejects.toThrow(
            new Pinnacle.InternalServerError({
                error: "error",
            }),
        );
    });
});
