// This file was auto-generated by Fern from our API Definition.

import * as Pinnacle from "../../../src/api/index";
import { PinnacleClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("TollFree", () => {
    test("autofill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            additionalInfo: "Please autofill missing campaign fields using my brand profile",
            campaignId: "dlc_1234567890",
        };
        const rawResponseBody = {
            campaignId: "tf_1234567890",
            keywords: {
                HELP: {
                    message:
                        "Pinnacle Software Development Inc.: For assistance, visit https://pinnacle.sh/support or email founders@trypinnacle.app. Msg&data rates may apply. Reply STOP to cancel.",
                },
                OPT_IN: {
                    message:
                        "Pinnacle Software Development Inc.: You're enrolled in account & security alerts. Msg&data rates may apply. Message frequency varies. Reply HELP for help, STOP to cancel. Terms: https://pinnacle.sh/terms/ Privacy: https://pinnacle.sh/privacy/",
                    keywords: ["START", "SUBSCRIBE"],
                },
            },
            links: {
                privacyPolicy: "https://www.pinnacle.sh/privacy",
                termsOfService: "https://www.pinnacle.sh/terms",
            },
            monthlyVolume: "10,000",
            name: "Pinnacle",
            optIn: {
                method: "PAPER",
                url: "https://www.pinnacle.sh/opt-in",
                workflowDescription:
                    "End users opt-in when filling out the in-person intake forms where they will write their phone numbers and check a box indicating that they've opted in to messages. Link to paper form: https://www.pinnacle.sh/opt-in",
            },
            options: { ageGated: false },
            productionMessageContent:
                "• Hi [First Name], your order #[Order ID] has shipped and will arrive [Date]. Track here: [URL]. Reply HELP for help or STOP to unsubscribe.\n• Heads up! [Friend Name] shared 3 photos. Reply VIEW to see them. Reply HELP for help or STOP to unsubscribe.\n• Hello [First Name]! I'm Pinnacle's virtual assistant. How can I help you today? Ask about order status, account updates, photo sharing, or more. Reply HELP for assistance or STOP to unsubscribe.",
            useCase: {
                summary:
                    "Customers who have opted into text messages can interact with our automated SMS chatbot to receive transaction-driven notifications (order status, shipping updates, account alerts), ask support questions, share photos with friends, and manage their account details via simple, conversational text flows. All messages are transactional or interactive flows customers opt into. Users can send images (e.g., receipts) and get guided replies.",
                value: "CHATBOT",
            },
            brand: "b_1234567890",
        };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/autofill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.tollFree.autofill({
            additionalInfo: "Please autofill missing campaign fields using my brand profile",
            campaignId: "dlc_1234567890",
        });
        expect(response).toEqual({
            campaignId: "tf_1234567890",
            keywords: {
                HELP: {
                    message:
                        "Pinnacle Software Development Inc.: For assistance, visit https://pinnacle.sh/support or email founders@trypinnacle.app. Msg&data rates may apply. Reply STOP to cancel.",
                },
                OPT_IN: {
                    message:
                        "Pinnacle Software Development Inc.: You're enrolled in account & security alerts. Msg&data rates may apply. Message frequency varies. Reply HELP for help, STOP to cancel. Terms: https://pinnacle.sh/terms/ Privacy: https://pinnacle.sh/privacy/",
                    keywords: ["START", "SUBSCRIBE"],
                },
            },
            links: {
                privacyPolicy: "https://www.pinnacle.sh/privacy",
                termsOfService: "https://www.pinnacle.sh/terms",
            },
            monthlyVolume: "10,000",
            name: "Pinnacle",
            optIn: {
                method: "PAPER",
                url: "https://www.pinnacle.sh/opt-in",
                workflowDescription:
                    "End users opt-in when filling out the in-person intake forms where they will write their phone numbers and check a box indicating that they've opted in to messages. Link to paper form: https://www.pinnacle.sh/opt-in",
            },
            options: {
                ageGated: false,
            },
            productionMessageContent:
                "\u2022 Hi [First Name], your order #[Order ID] has shipped and will arrive [Date]. Track here: [URL]. Reply HELP for help or STOP to unsubscribe.\n\u2022 Heads up! [Friend Name] shared 3 photos. Reply VIEW to see them. Reply HELP for help or STOP to unsubscribe.\n\u2022 Hello [First Name]! I'm Pinnacle's virtual assistant. How can I help you today? Ask about order status, account updates, photo sharing, or more. Reply HELP for assistance or STOP to unsubscribe.",
            useCase: {
                summary:
                    "Customers who have opted into text messages can interact with our automated SMS chatbot to receive transaction-driven notifications (order status, shipping updates, account alerts), ask support questions, share photos with friends, and manage their account details via simple, conversational text flows. All messages are transactional or interactive flows customers opt into. Users can send images (e.g., receipts) and get guided replies.",
                value: "CHATBOT",
            },
            brand: "b_1234567890",
        });
    });

    test("autofill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/autofill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.autofill({});
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("autofill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/autofill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.autofill({});
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("autofill (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/autofill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.autofill({});
        }).rejects.toThrow(Pinnacle.ForbiddenError);
    });

    test("autofill (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/autofill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.autofill({});
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            brand: {
                address: "500 Folsom Street, San Francisco, CA 94105",
                contact: {
                    email: "janedoe1@pinnacle.example",
                    name: "Jane Doe",
                    phone: "+14155550123",
                    title: "Customer Support Specialist",
                },
                dba: "Pinnacle RCS",
                description: "description",
                ein: "12-3456789",
                email: "founders@trypinnacle.app",
                name: "Pinnacle",
                sector: "TECHNOLOGY",
                type: "PRIVATE_PROFIT",
                entityType: "LLC",
                website: "https://www.pinnacle.sh/",
                createdAt: "2024-08-17T08:00:30.632",
                id: "b_1234567890",
                isArchived: false,
                status: "VERIFIED",
                updatedAt: "2024-12-09T10:03:54.934",
            },
            status: "VERIFIED",
            campaignId: "tf_1234567890",
            keywords: {
                HELP: {
                    message:
                        "Pinnacle Software Development Inc.: For assistance, visit https://pinnacle.sh/support or email founders@trypinnacle.app. Msg&data rates may apply. Reply STOP to cancel.",
                },
                OPT_IN: {
                    message:
                        "Pinnacle Software Development Inc.: You're enrolled in account & security alerts. Msg&data rates may apply. Message frequency varies. Reply HELP for help, STOP to cancel. Terms: https://pinnacle.sh/terms/ Privacy: https://pinnacle.sh/privacy/",
                    keywords: ["START", "SUBSCRIBE"],
                },
            },
            links: {
                privacyPolicy: "https://www.pinnacle.sh/privacy",
                termsOfService: "https://www.pinnacle.sh/terms",
            },
            monthlyVolume: "10,000",
            name: "Pinnacle's Account Notifications",
            optIn: {
                method: "PAPER",
                url: "https://www.pinnacle.sh/opt-in",
                workflowDescription:
                    "End users opt-in when filling out the in-person intake forms where they will write their phone numbers and check a box indicating that they've opted in to messages. Link to paper form: https://www.pinnacle.sh/opt-in",
            },
            options: { ageGated: false },
            productionMessageContent:
                "• Hi [First Name], your order #[Order ID] has shipped and will arrive [Date]. Track here: [URL]. Reply HELP for help or STOP to unsubscribe.\n• Heads up! [Friend Name] shared 3 photos. Reply VIEW to see them. Reply HELP for help or STOP to unsubscribe.\n• Hello [First Name]! I'm Pinnacle's virtual assistant. How can I help you today? Ask about order status, account updates, photo sharing, or more. Reply HELP for assistance or STOP to unsubscribe.",
            useCase: {
                summary:
                    "Customers who have opted into text messages can interact with our automated SMS chatbot to receive transaction-driven notifications (order status, shipping updates, account alerts), ask support questions, share photos with friends, and manage their account details via simple, conversational text flows. All messages are transactional or interactive flows customers opt into. Users can send images (e.g., receipts) and get guided replies.",
                value: "CHATBOT",
            },
        };
        server
            .mockEndpoint()
            .get("/campaigns/toll-free/tf_1234567890")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.tollFree.get("tf_1234567890");
        expect(response).toEqual({
            brand: {
                address: "500 Folsom Street, San Francisco, CA 94105",
                contact: {
                    email: "janedoe1@pinnacle.example",
                    name: "Jane Doe",
                    phone: "+14155550123",
                    title: "Customer Support Specialist",
                },
                dba: "Pinnacle RCS",
                description: "description",
                ein: "12-3456789",
                email: "founders@trypinnacle.app",
                name: "Pinnacle",
                sector: "TECHNOLOGY",
                type: "PRIVATE_PROFIT",
                entityType: "LLC",
                website: "https://www.pinnacle.sh/",
                createdAt: "2024-08-17T08:00:30.632",
                id: "b_1234567890",
                isArchived: false,
                status: "VERIFIED",
                updatedAt: "2024-12-09T10:03:54.934",
            },
            status: "VERIFIED",
            campaignId: "tf_1234567890",
            keywords: {
                HELP: {
                    message:
                        "Pinnacle Software Development Inc.: For assistance, visit https://pinnacle.sh/support or email founders@trypinnacle.app. Msg&data rates may apply. Reply STOP to cancel.",
                },
                OPT_IN: {
                    message:
                        "Pinnacle Software Development Inc.: You're enrolled in account & security alerts. Msg&data rates may apply. Message frequency varies. Reply HELP for help, STOP to cancel. Terms: https://pinnacle.sh/terms/ Privacy: https://pinnacle.sh/privacy/",
                    keywords: ["START", "SUBSCRIBE"],
                },
            },
            links: {
                privacyPolicy: "https://www.pinnacle.sh/privacy",
                termsOfService: "https://www.pinnacle.sh/terms",
            },
            monthlyVolume: "10,000",
            name: "Pinnacle's Account Notifications",
            optIn: {
                method: "PAPER",
                url: "https://www.pinnacle.sh/opt-in",
                workflowDescription:
                    "End users opt-in when filling out the in-person intake forms where they will write their phone numbers and check a box indicating that they've opted in to messages. Link to paper form: https://www.pinnacle.sh/opt-in",
            },
            options: {
                ageGated: false,
            },
            productionMessageContent:
                "\u2022 Hi [First Name], your order #[Order ID] has shipped and will arrive [Date]. Track here: [URL]. Reply HELP for help or STOP to unsubscribe.\n\u2022 Heads up! [Friend Name] shared 3 photos. Reply VIEW to see them. Reply HELP for help or STOP to unsubscribe.\n\u2022 Hello [First Name]! I'm Pinnacle's virtual assistant. How can I help you today? Ask about order status, account updates, photo sharing, or more. Reply HELP for assistance or STOP to unsubscribe.",
            useCase: {
                summary:
                    "Customers who have opted into text messages can interact with our automated SMS chatbot to receive transaction-driven notifications (order status, shipping updates, account alerts), ask support questions, share photos with friends, and manage their account details via simple, conversational text flows. All messages are transactional or interactive flows customers opt into. Users can send images (e.g., receipts) and get guided replies.",
                value: "CHATBOT",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/campaigns/toll-free/campaignId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.get("campaignId");
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .get("/campaigns/toll-free/campaignId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.get("campaignId");
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .get("/campaigns/toll-free/campaignId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.get("campaignId");
        }).rejects.toThrow(Pinnacle.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/campaigns/toll-free/campaignId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.get("campaignId");
        }).rejects.toThrow(Pinnacle.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .get("/campaigns/toll-free/campaignId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.get("campaignId");
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });

    test("submit (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/submit/tf_1234567890")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.tollFree.submit("tf_1234567890");
        expect(response).toEqual({
            success: true,
        });
    });

    test("submit (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/submit/campaignId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.submit("campaignId");
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("submit (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/submit/campaignId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.submit("campaignId");
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("submit (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/submit/campaignId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.submit("campaignId");
        }).rejects.toThrow(Pinnacle.ForbiddenError);
    });

    test("submit (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/submit/campaignId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.submit("campaignId");
        }).rejects.toThrow(Pinnacle.NotFoundError);
    });

    test("submit (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/submit/campaignId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.submit("campaignId");
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });

    test("upsert (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            brand: "b_1234567890",
            campaignId: "tf_1234567890",
            keywords: {
                HELP: {
                    message:
                        "Pinnacle Software Development Inc.: For assistance, visit https://pinnacle.sh/support or email founders@trypinnacle.app. Msg&data rates may apply. Reply STOP to cancel.",
                },
                OPT_IN: {
                    message:
                        "Pinnacle Software Development Inc.: You're enrolled in account & security alerts. Msg&data rates may apply. Message frequency varies. Reply HELP for help, STOP to cancel. Terms: https://pinnacle.sh/terms/ Privacy: https://pinnacle.sh/privacy/",
                    keywords: ["START", "SUBSCRIBE"],
                },
            },
            links: {
                privacyPolicy: "https://www.pinnacle.sh/privacy",
                termsOfService: "https://www.pinnacle.sh/terms",
            },
            monthlyVolume: "10,000",
            name: "Pinnacle",
            optIn: {
                method: "PAPER",
                url: "https://www.pinnacle.sh/opt-in",
                workflowDescription:
                    "End users opt-in when filling out the in-person intake forms where they will write their phone numbers and check a box indicating that they've opted in to messages. Link to paper form: https://www.pinnacle.sh/opt-in",
            },
            options: { ageGated: false },
            productionMessageContent:
                "Hi [First Name], your order #[Order ID] has shipped and will arrive [Date]. Track here: [URL]. Reply HELP for help or STOP to unsubscribe.",
            useCase: {
                summary:
                    "Customers who have opted into text messages can interact with our automated SMS chatbot to receive transaction-driven notifications (order status, shipping updates, account alerts), ask support questions, share photos with friends, and manage their account details via simple, conversational text flows. All messages are transactional or interactive flows customers opt into. Users can send images (e.g., receipts) and get guided replies.",
                value: "CHATBOT",
            },
        };
        const rawResponseBody = {
            brand: {
                address: "500 Folsom Street, San Francisco, CA 94105",
                contact: {
                    email: "janedoe1@pinnacle.example",
                    name: "Jane Doe",
                    phone: "+14155550123",
                    title: "Customer Support Specialist",
                },
                dba: "Pinnacle RCS",
                description: "description",
                ein: "12-3456789",
                email: "founders@trypinnacle.app",
                name: "Pinnacle",
                sector: "TECHNOLOGY",
                type: "PRIVATE_PROFIT",
                entityType: "LLC",
                website: "https://www.pinnacle.sh/",
                createdAt: "2024-08-17T08:00:30.632",
                id: "b_1234567890",
                isArchived: false,
                status: "VERIFIED",
                updatedAt: "2024-12-09T10:03:54.934",
            },
            status: "VERIFIED",
            campaignId: "tf_1234567890",
            keywords: {
                HELP: {
                    message:
                        "Pinnacle Software Development Inc.: For assistance, visit https://pinnacle.sh/support or email founders@trypinnacle.app. Msg&data rates may apply. Reply STOP to cancel.",
                },
                OPT_IN: {
                    message:
                        "Pinnacle Software Development Inc.: You're enrolled in account & security alerts. Msg&data rates may apply. Message frequency varies. Reply HELP for help, STOP to cancel. Terms: https://pinnacle.sh/terms/ Privacy: https://pinnacle.sh/privacy/",
                    keywords: ["START", "SUBSCRIBE"],
                },
            },
            links: {
                privacyPolicy: "https://www.pinnacle.sh/privacy",
                termsOfService: "https://www.pinnacle.sh/terms",
            },
            monthlyVolume: "10,000",
            name: "Pinnacle's Account Notifications",
            optIn: {
                method: "PAPER",
                url: "https://www.pinnacle.sh/opt-in",
                workflowDescription:
                    "End users opt-in when filling out the in-person intake forms where they will write their phone numbers and check a box indicating that they've opted in to messages. Link to paper form: https://www.pinnacle.sh/opt-in",
            },
            options: { ageGated: false },
            productionMessageContent:
                "• Hi [First Name], your order #[Order ID] has shipped and will arrive [Date]. Track here: [URL]. Reply HELP for help or STOP to unsubscribe.\n• Heads up! [Friend Name] shared 3 photos. Reply VIEW to see them. Reply HELP for help or STOP to unsubscribe.\n• Hello [First Name]! I'm Pinnacle's virtual assistant. How can I help you today? Ask about order status, account updates, photo sharing, or more. Reply HELP for assistance or STOP to unsubscribe.",
            useCase: {
                summary:
                    "Customers who have opted into text messages can interact with our automated SMS chatbot to receive transaction-driven notifications (order status, shipping updates, account alerts), ask support questions, share photos with friends, and manage their account details via simple, conversational text flows. All messages are transactional or interactive flows customers opt into. Users can send images (e.g., receipts) and get guided replies.",
                value: "CHATBOT",
            },
        };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.tollFree.upsert({
            brand: "b_1234567890",
            campaignId: "tf_1234567890",
            keywords: {
                HELP: {
                    message:
                        "Pinnacle Software Development Inc.: For assistance, visit https://pinnacle.sh/support or email founders@trypinnacle.app. Msg&data rates may apply. Reply STOP to cancel.",
                },
                OPT_IN: {
                    message:
                        "Pinnacle Software Development Inc.: You're enrolled in account & security alerts. Msg&data rates may apply. Message frequency varies. Reply HELP for help, STOP to cancel. Terms: https://pinnacle.sh/terms/ Privacy: https://pinnacle.sh/privacy/",
                    keywords: ["START", "SUBSCRIBE"],
                },
            },
            links: {
                privacyPolicy: "https://www.pinnacle.sh/privacy",
                termsOfService: "https://www.pinnacle.sh/terms",
            },
            monthlyVolume: "10,000",
            name: "Pinnacle",
            optIn: {
                method: "PAPER",
                url: "https://www.pinnacle.sh/opt-in",
                workflowDescription:
                    "End users opt-in when filling out the in-person intake forms where they will write their phone numbers and check a box indicating that they've opted in to messages. Link to paper form: https://www.pinnacle.sh/opt-in",
            },
            options: {
                ageGated: false,
            },
            productionMessageContent:
                "Hi [First Name], your order #[Order ID] has shipped and will arrive [Date]. Track here: [URL]. Reply HELP for help or STOP to unsubscribe.",
            useCase: {
                summary:
                    "Customers who have opted into text messages can interact with our automated SMS chatbot to receive transaction-driven notifications (order status, shipping updates, account alerts), ask support questions, share photos with friends, and manage their account details via simple, conversational text flows. All messages are transactional or interactive flows customers opt into. Users can send images (e.g., receipts) and get guided replies.",
                value: "CHATBOT",
            },
        });
        expect(response).toEqual({
            brand: {
                address: "500 Folsom Street, San Francisco, CA 94105",
                contact: {
                    email: "janedoe1@pinnacle.example",
                    name: "Jane Doe",
                    phone: "+14155550123",
                    title: "Customer Support Specialist",
                },
                dba: "Pinnacle RCS",
                description: "description",
                ein: "12-3456789",
                email: "founders@trypinnacle.app",
                name: "Pinnacle",
                sector: "TECHNOLOGY",
                type: "PRIVATE_PROFIT",
                entityType: "LLC",
                website: "https://www.pinnacle.sh/",
                createdAt: "2024-08-17T08:00:30.632",
                id: "b_1234567890",
                isArchived: false,
                status: "VERIFIED",
                updatedAt: "2024-12-09T10:03:54.934",
            },
            status: "VERIFIED",
            campaignId: "tf_1234567890",
            keywords: {
                HELP: {
                    message:
                        "Pinnacle Software Development Inc.: For assistance, visit https://pinnacle.sh/support or email founders@trypinnacle.app. Msg&data rates may apply. Reply STOP to cancel.",
                },
                OPT_IN: {
                    message:
                        "Pinnacle Software Development Inc.: You're enrolled in account & security alerts. Msg&data rates may apply. Message frequency varies. Reply HELP for help, STOP to cancel. Terms: https://pinnacle.sh/terms/ Privacy: https://pinnacle.sh/privacy/",
                    keywords: ["START", "SUBSCRIBE"],
                },
            },
            links: {
                privacyPolicy: "https://www.pinnacle.sh/privacy",
                termsOfService: "https://www.pinnacle.sh/terms",
            },
            monthlyVolume: "10,000",
            name: "Pinnacle's Account Notifications",
            optIn: {
                method: "PAPER",
                url: "https://www.pinnacle.sh/opt-in",
                workflowDescription:
                    "End users opt-in when filling out the in-person intake forms where they will write their phone numbers and check a box indicating that they've opted in to messages. Link to paper form: https://www.pinnacle.sh/opt-in",
            },
            options: {
                ageGated: false,
            },
            productionMessageContent:
                "\u2022 Hi [First Name], your order #[Order ID] has shipped and will arrive [Date]. Track here: [URL]. Reply HELP for help or STOP to unsubscribe.\n\u2022 Heads up! [Friend Name] shared 3 photos. Reply VIEW to see them. Reply HELP for help or STOP to unsubscribe.\n\u2022 Hello [First Name]! I'm Pinnacle's virtual assistant. How can I help you today? Ask about order status, account updates, photo sharing, or more. Reply HELP for assistance or STOP to unsubscribe.",
            useCase: {
                summary:
                    "Customers who have opted into text messages can interact with our automated SMS chatbot to receive transaction-driven notifications (order status, shipping updates, account alerts), ask support questions, share photos with friends, and manage their account details via simple, conversational text flows. All messages are transactional or interactive flows customers opt into. Users can send images (e.g., receipts) and get guided replies.",
                value: "CHATBOT",
            },
        });
    });

    test("upsert (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.upsert();
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("upsert (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.upsert();
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("upsert (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.upsert();
        }).rejects.toThrow(Pinnacle.ForbiddenError);
    });

    test("upsert (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.upsert();
        }).rejects.toThrow(Pinnacle.NotFoundError);
    });

    test("upsert (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.upsert();
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });

    test("validate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            additionalInfo: "Please validate this DLC campaign for 10DLC compliance",
            campaignId: "dlc_1234567890",
        };
        const rawResponseBody = {
            errors: [{ description: "description", example: "example", field: "field" }],
            is_valid: true,
        };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.tollFree.validate({
            additionalInfo: "Please validate this DLC campaign for 10DLC compliance",
            campaignId: "dlc_1234567890",
        });
        expect(response).toEqual({
            errors: [
                {
                    description: "description",
                    example: "example",
                    field: "field",
                },
            ],
            is_valid: true,
        });
    });

    test("validate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { campaignId: "campaignId" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.validate({
                campaignId: "campaignId",
            });
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("validate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { campaignId: "campaignId" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.validate({
                campaignId: "campaignId",
            });
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("validate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { campaignId: "campaignId" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.validate({
                campaignId: "campaignId",
            });
        }).rejects.toThrow(Pinnacle.ForbiddenError);
    });

    test("validate (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { campaignId: "campaignId" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/campaigns/toll-free/validate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.campaigns.tollFree.validate({
                campaignId: "campaignId",
            });
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });
});
