// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface BrandsGetRequest {
    /**
     * Optional flag to mask the Employer Identification Number in the response for security purposes.<br>
     *
     * When you set this to true, the EIN value will be replaced with a masked placeholder instead of the actual number.
     */
    hideEIN?: boolean;
}
