// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "b_1234567890"
 *     }
 */
export interface GetBrandsRequest {
    /**
     * The unique identifier of the brand you want to retrieve from your account.
     * <br><br> This identifier is a string that always begins with the prefix `b_`, for example: `b_1234567890`.
     */
    id: string;
    /**
     * Optional flag to mask the Employer Identification Number in the response for security purposes.<br>
     *
     * When you set this to true, the EIN value will be replaced with a masked placeholder instead of the actual number.
     */
    hideEIN?: boolean;
}
