// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         address: "500 Folsom St, San Francisco, CA 94105",
 *         contact: {
 *             email: "michael.chen@trypinnacle.app",
 *             name: "Michael Chen",
 *             phone: "+14155551234",
 *             title: "Customer Support Representative"
 *         },
 *         dba: "Pinnacle RCS",
 *         description: "A developer-friendly, compliant API for SMS, MMS, and RCS, built to scale real conversations.",
 *         ein: "88-1234567",
 *         email: "founders@trypinnacle.app",
 *         id: "b_1234567890",
 *         name: "Pinnacle",
 *         sector: "TECHNOLOGY",
 *         type: "PRIVATE_PROFIT",
 *         entityType: "LLC",
 *         website: "https://www.pinnacle.sh"
 *     }
 */
export interface UpsertBrandParams {
    /** Primary brand address where the company is located. */
    address?: string | null;
    /** Contact information for the brand. */
    contact?: UpsertBrandParams.Contact | null;
    /** "Doing Business As" name - the public name the brand operates under. */
    dba?: string | null;
    /** Brief description of what the brand does. */
    description?: string | null;
    /** Brand's Employer Identification Number (EIN) assigned by the IRS. */
    ein?: string | null;
    /** Main contact email address for the brand. */
    email?: string | null;
    /**
     * The unique identifier of the brand you want to update.
     * <br><br> This identifier is a string that always begins with the prefix `b_`, for example: `b_1234567890`.
     */
    id?: string;
    /** Legal name of the brand as registered. */
    name?: string | null;
    /** Industry the brand operates in. */
    sector?: UpsertBrandParams.Sector | null;
    /** Legal structure of the brand. */
    type?: UpsertBrandParams.Type | null;
    /** Legal entity type of the brand. */
    entityType?: UpsertBrandParams.EntityType | null;
    /** Brand website URL. */
    website?: string | null;
}

export namespace UpsertBrandParams {
    /**
     * Contact information for the brand.
     */
    export interface Contact {
        /** Email address of the contact person. */
        email?: string | null;
        /** Full name of the contact person. */
        name?: string | null;
        /** Phone number of the contact person in E.164 format. */
        phone?: string | null;
        /** Job title of the contact person. */
        title?: string | null;
    }

    /** Industry the brand operates in. */
    export const Sector = {
        Agriculture: "AGRICULTURE",
        Communication: "COMMUNICATION",
        Construction: "CONSTRUCTION",
        Education: "EDUCATION",
        Energy: "ENERGY",
        Entertainment: "ENTERTAINMENT",
        Financial: "FINANCIAL",
        Gambling: "GAMBLING",
        Government: "GOVERNMENT",
        Healthcare: "HEALTHCARE",
        Hospitality: "HOSPITALITY",
        Insurance: "INSURANCE",
        Manufacturing: "MANUFACTURING",
        Ngo: "NGO",
        RealEstate: "REAL_ESTATE",
        Retail: "RETAIL",
        Technology: "TECHNOLOGY",
    } as const;
    export type Sector = (typeof Sector)[keyof typeof Sector];
    /** Legal structure of the brand. */
    export const Type = {
        Government: "GOVERNMENT",
        NonProfit: "NON_PROFIT",
        PrivateProfit: "PRIVATE_PROFIT",
        PublicProfit: "PUBLIC_PROFIT",
        SoleProprietor: "SOLE_PROPRIETOR",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** Legal entity type of the brand. */
    export const EntityType = {
        Llc: "LLC",
        SoleProprietorship: "SOLE_PROPRIETORSHIP",
        Partnership: "PARTNERSHIP",
        Corp: "CORP",
        SCorp: "S_CORP",
    } as const;
    export type EntityType = (typeof EntityType)[keyof typeof EntityType];
}
