/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../../../../index.js";

/**
 * @example
 *     {
 *         address: "500 Folsom St, San Francisco, CA 94105",
 *         contact: {
 *             email: "michael.chen@trypinnacle.app",
 *             name: "Michael Chen",
 *             phone: "+14155551234",
 *             title: "Customer Support Representative"
 *         },
 *         dba: "Pinnacle RCS",
 *         description: "A developer-friendly, compliant API for SMS, MMS, and RCS, built to scale real conversations.",
 *         ein: "88-1234567",
 *         email: "founders@trypinnacle.app",
 *         id: 1,
 *         name: "Pinnacle",
 *         sector: "TECHNOLOGY",
 *         type: "PRIVATE_PROFIT",
 *         website: "https://www.pinnacle.sh"
 *     }
 */
export interface UpsertBrandSchema {
    /** Primary business address where your company is located. */
    address?: string | null;
    /** Contact information for this business. */
    contact?: UpsertBrandSchema.Contact | null;
    /** "Doing Business As" name - the public name your business operates under. */
    dba?: string | null;
    /** Brief description of what your business does. */
    description?: string | null;
    /** Your business's Employer Identification Number (EIN) assigned by the IRS. */
    ein?: string | null;
    /** Main contact email address for your business. */
    email?: string | null;
    /** Brand ID - include only when updating an existing brand, omit to create a new one. */
    id?: number;
    /** Legal name of your business as registered. */
    name?: string | null;
    sector?: Pinnacle.CompanySectorReq;
    type?: Pinnacle.CompanyTypeReq;
    /** Your business website URL. */
    website?: string | null;
}

export namespace UpsertBrandSchema {
    /**
     * Contact information for this business.
     */
    export interface Contact {
        /** Email address of the contact person. */
        email?: string | null;
        /** Full name of the contact person. */
        name?: string | null;
        /** Phone number of the contact person in E.164 format. */
        phone?: string | null;
        /** Job title of the contact person. */
        title?: string | null;
    }
}
