/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pinnacle from "../../../../index";

/**
 * @example
 *     {}
 */
export interface CompanyUpdateRequest {
    /** Optional company ID. If provided, updates existing company. If not provided, creates a new company. */
    companyId?: string;
    company?: Pinnacle.Company;
    companyContact?: Pinnacle.CompanyContact;
    messaging?: Pinnacle.Messaging;
    pointOfContact?: Pinnacle.PointOfContact;
    optionals?: Pinnacle.Optionals;
}
