/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Pinnacle from "../../api/index";
import * as core from "../../core";

export const ActionType: core.serialization.Schema<serializers.ActionType.Raw, Pinnacle.ActionType> =
    core.serialization.enum_(["openUrl", "call", "trigger", "requestUserLocation", "scheduleEvent", "sendLocation"]);

export declare namespace ActionType {
    type Raw = "openUrl" | "call" | "trigger" | "requestUserLocation" | "scheduleEvent" | "sendLocation";
}
