/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Pinnacle from "../../api/index";
import * as core from "../../core";
import { PhoneNumber } from "./PhoneNumber";
import { BasicRcsMessage } from "./BasicRcsMessage";
import { Action } from "./Action";

export const BasicRcs: core.serialization.ObjectSchema<serializers.BasicRcs.Raw, Pinnacle.BasicRcs> =
    core.serialization.object({
        phoneNumber: core.serialization.property("phone_number", PhoneNumber.optional()),
        messageType: core.serialization.property("message_type", core.serialization.stringLiteral("basic-rcs")),
        message: BasicRcsMessage,
        quickReplies: core.serialization.property("quick_replies", core.serialization.list(Action).optional()),
    });

export declare namespace BasicRcs {
    interface Raw {
        phone_number?: PhoneNumber.Raw | null;
        message_type: "basic-rcs";
        message: BasicRcsMessage.Raw;
        quick_replies?: Action.Raw[] | null;
    }
}
