/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Pinnacle from "../../api/index";
import * as core from "../../core";
import { CardStyleImageAlignment } from "./CardStyleImageAlignment";
import { CardStyleMediaHeight } from "./CardStyleMediaHeight";
import { CardStyleWidth } from "./CardStyleWidth";
import { CardStyleOrientation } from "./CardStyleOrientation";

export const CardStyle: core.serialization.ObjectSchema<serializers.CardStyle.Raw, Pinnacle.CardStyle> =
    core.serialization.object({
        imageAlignment: core.serialization.property("image_alignment", CardStyleImageAlignment.optional()),
        mediaHeight: core.serialization.property("media_height", CardStyleMediaHeight.optional()),
        thumbnailUrl: core.serialization.property("thumbnail_url", core.serialization.string().optional()),
        width: CardStyleWidth.optional(),
        orientation: CardStyleOrientation.optional(),
    });

export declare namespace CardStyle {
    interface Raw {
        image_alignment?: CardStyleImageAlignment.Raw | null;
        media_height?: CardStyleMediaHeight.Raw | null;
        thumbnail_url?: string | null;
        width?: CardStyleWidth.Raw | null;
        orientation?: CardStyleOrientation.Raw | null;
    }
}
