/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Pinnacle from "../../api/index";
import * as core from "../../core";

export const GetCheckRcsResponse: core.serialization.ObjectSchema<
    serializers.GetCheckRcsResponse.Raw,
    Pinnacle.GetCheckRcsResponse
> = core.serialization.object({
    success: core.serialization.boolean().optional(),
    rcsEnabled: core.serialization.boolean().optional(),
    message: core.serialization.string().optional(),
});

export declare namespace GetCheckRcsResponse {
    interface Raw {
        success?: boolean | null;
        rcsEnabled?: boolean | null;
        message?: string | null;
    }
}
