/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Pinnacle from "../../api/index";
import * as core from "../../core";
import { RcsMessage } from "./RcsMessage";
import { SmsMessage } from "./SmsMessage";

export const SendAnRcsMessageRequestBody: core.serialization.Schema<
    serializers.SendAnRcsMessageRequestBody.Raw,
    Pinnacle.SendAnRcsMessageRequestBody
> = core.serialization.undiscriminatedUnion([RcsMessage, SmsMessage]);

export declare namespace SendAnRcsMessageRequestBody {
    type Raw = RcsMessage.Raw | SmsMessage.Raw;
}
