/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Pinnacle from "../../api/index";
import * as core from "../../core";
import { CardRcs } from "./CardRcs";
import { Sms } from "./Sms";
import { BasicRcs } from "./BasicRcs";
import { MediaRcs } from "./MediaRcs";
import { CarouselRcs } from "./CarouselRcs";

export const SendMessageRequest: core.serialization.Schema<
    serializers.SendMessageRequest.Raw,
    Pinnacle.SendMessageRequest
> = core.serialization.undiscriminatedUnion([CardRcs, Sms, BasicRcs, MediaRcs, CarouselRcs]);

export declare namespace SendMessageRequest {
    type Raw = CardRcs.Raw | Sms.Raw | BasicRcs.Raw | MediaRcs.Raw | CarouselRcs.Raw;
}
