/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Pinnacle from "../../api/index";
import * as core from "../../core";

export const UpdateSettingsResponse: core.serialization.ObjectSchema<
    serializers.UpdateSettingsResponse.Raw,
    Pinnacle.UpdateSettingsResponse
> = core.serialization.object({
    message: core.serialization.string().optional(),
});

export declare namespace UpdateSettingsResponse {
    interface Raw {
        message?: string | null;
    }
}
