// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../../../../../../index.js";

/**
 * @example
 *     {
 *         agent: {
 *             color: "#000000",
 *             description: "Experience the power of RCS messaging with interactive demos. Test rich features like carousels, suggested replies, and media sharing. Get started with our developer-friendly APIs.",
 *             emails: [{
 *                     email: "founders@trypinnacle.app",
 *                     label: "Email Us"
 *                 }],
 *             heroUrl: "https://pncl.to/D6pDSqGxqgfbCfQmw4gXdnlHu4uSB4",
 *             iconUrl: "https://pncl.to/mq_tdIDenRb5eYpJiM8-3THCaUBrZP",
 *             name: "Pinnacle - RCS Demo",
 *             phones: [{
 *                     label: "Contact us directly",
 *                     phone: "+14154467821"
 *                 }],
 *             websites: [{
 *                     label: "Get started with Pinnacle",
 *                     url: "https://www.trypinnacle.app/"
 *                 }]
 *         },
 *         brand: "b_1234567890",
 *         campaignId: "rcs_1234567890",
 *         expectedAgentResponses: ["Here are the things I can help you with.", "I can assist you with booking an appointment, or you may choose to book manually.", "Here are the available times to connect with a representative tomorrow.", "Your appointment has been scheduled."],
 *         links: {
 *             privacyPolicy: "https://www.trypinnacle.app/privacy",
 *             termsOfService: "https://www.trypinnacle.app/terms"
 *         },
 *         useCase: {
 *             behavior: "Pinnacle is a developer-focused RCS assistant that helps teams design, test, and optimize rich messaging experiences across SMS, MMS, and RCS. The agent acts as both an \u201Conboarding guide\u201D for new customers and a \u201Cbest-practices coach\u201D for existing teams exploring higher-value RCS workflows like rich cards, carousels, and suggested actions.<br>\nThe agent delivers a mix of operational updates and educational content (2\u20136 messages/month). Content includes important platform notices (e.g., deliverability or throughput changes), implementation tips with sample RCS templates, and personalized recommendations on how to upgrade existing SMS campaigns into richer, higher-converting RCS conversations.\n",
 *             value: "OTHER"
 *         },
 *         optInTermsAndConditions: "We ensure consent through an explicit opt-in process that follows 10DLC best practices.Users must agree to receive messages from Pinnacle before the agent sends them any messages.<br>\nUsers agree to these messages by signing an opt-in paper form that they can be found online at https://www.pinnacle.sh/opt-in. We only send messages once users have filled out the form and submitted it to us via email or through the dashboard.\n",
 *         messagingType: "MULTI_USE",
 *         carrierDescription: "Demonstrate the power of RCS to medium and large companies already sending massive SMS/MMS volumes through our platform. These clients send conversational messages in industries such as commerce, appointments, and customer support.",
 *         keywords: {
 *             HELP: {
 *                 message: "Email founders@trypinnacle.app for support.",
 *                 keywords: ["HELP", "SUPPORT"]
 *             },
 *             OPT_IN: {
 *                 message: "Welcome back to Pinnacle!<br>\n\uD83D\uDD14 You're now subscribed to Pinnacle - RCS Demo and will continue receiving important updates and news. Feel free to contact this us at any time for help.<br>\n\nReply STOP to opt out and HELP for support. Message & rates may apply.\n",
 *                 keywords: ["START", "SUBSCRIBE"]
 *             },
 *             OPT_OUT: {
 *                 message: "You've been unsubscribed from Pinnacle - RCS Demo and will no longer receive notifications. If you ever change your mind, reply START or SUBSCRIBE to rejoin anytime.",
 *                 keywords: ["STOP", "UNSUBSCRIBE", "END"]
 *             }
 *         },
 *         traffic: {
 *             monthlyWebsite: 10000,
 *             monthlyRcsEstimate: 10000
 *         },
 *         agentTriggers: "The agent sends the first message when the user subscribes to Pinnacle. Messages are based on user actions such as pressing suggestion buttons. External triggers such as reminders can be setup by users in advance for a later time.",
 *         interactionDescription: "The agent's primary interaction will be customer service \u2014 helping users with questions, troubleshooting issues, and providing quick assistance through chat. Other interactions include appointment management and sending notifications to the user.",
 *         isConversational: true,
 *         ctaLanguage: "By checking this box and submitting this form, you consent to receive transactional text messages for support, appointment, and reminder messages from Pinnacle Software Development Inc. Reply STOP to opt out. Reply HELP for help. Standard message and data rates may apply. Message frequency may vary. View our Terms and Conditions at https://www.pinnacle.sh/terms. View our Privacy Policy at https://www.pinnacle.sh/privacy.",
 *         demoTrigger: "Text \"START\" to trigger the flow."
 *     }
 */
export interface UpsertRcsCampaignParams {
    /** Create an agent for the campaign. */
    agent?: UpsertRcsCampaignParams.Agent;
    /** Unique identifier for the brand. */
    brand?: string;
    /** Unique identifier for the campaign. */
    campaignId?: string;
    /**
     * List of what the agent might say to users. See the [Expected Agent Responses](/guides/campaigns/rcs-compliance#expected-agent-responses) section for requirements. <br><br>
     * **Limit:** 1 to 5
     */
    expectedAgentResponses?: string[];
    /** Legal documentation links. */
    links?: UpsertRcsCampaignParams.Links;
    /** Use case classification for the campaign. */
    useCase?: UpsertRcsCampaignParams.UseCase;
    /** Details on how opt-in is acquired. If it is done through a website or app, provide the link. See the [Opt-In Terms and Conditions](/guides/campaigns/rcs-compliance#opt-in-terms-and-conditions) section for requirements. */
    optInTermsAndConditions?: string;
    messagingType?: Pinnacle.RcsMessagingTypeEnum;
    /** Description of the agent's purpose, shown to carriers for approval. See the [Carrier Description](/guides/campaigns/rcs-compliance#carrier-description) section for requirements. */
    carrierDescription?: string;
    keywords?: UpsertRcsCampaignParams.Keywords;
    traffic?: UpsertRcsCampaignParams.Traffic;
    /** Explanation of how the agent is triggered. This includes how the first message is delivered, whether messages follow a schedule or triggered by user actions, and any external triggers. See the [Agent Triggers](/guides/campaigns/rcs-compliance#agent-triggers) section for requirements. */
    agentTriggers?: string;
    /** Description of all agent interactions, including primary and secondary use cases. See the [Interaction Description](/guides/campaigns/rcs-compliance#interaction-description) section for requirements. */
    interactionDescription?: string;
    /** Whether the agent supports conversational flows or respond to P2A messages from the users. Set to false for one-way messages from agent to user. */
    isConversational?: boolean;
    /** Required text that appears next to the opt-in checkbox for your opt-in form. This checkbox has to be unchecked by default. See the [CTA Language](/guides/campaigns/rcs-compliance#cta-language-opt-in-disclosure) section for requirements. */
    ctaLanguage?: string;
    /** Instructions on how an external reviewer can trigger messages and an example flow from the agent. This is usually an inbound text message to the agent that will start a flow of messages between the agent and the user. See the [Demo Trigger](/guides/campaigns/rcs-compliance#demo-trigger) section for requirements. */
    demoTrigger?: string;
}

export namespace UpsertRcsCampaignParams {
    /**
     * Create an agent for the campaign.
     */
    export interface Agent {
        /**
         * Color of the agent's buttons. <br>
         *
         * Must have sufficient contrast with white.
         */
        color?: string;
        /**
         * Description of the agent. <br>
         *
         * Be clear, concise, user-focused, and highlight what the agent does and the benefits it provides for the user.
         */
        description?: string;
        /**
         * List of emails. <br><br>
         * **Limit:** 1 to 3
         */
        emails?: Agent.Emails.Item[];
        /** Link to the agent's hero. Hero must be an image file with dimensions 1440x448px. */
        heroUrl?: string;
        /** Link to the agent's icon. Icon must be an image file with dimensions 224x224px. */
        iconUrl?: string;
        /**
         * Name of the agent. <br>
         *
         * Recommended format: [Brand Name] - [1-2 word description of purpose]
         */
        name?: string;
        /**
         * List of phone numbers. <br><br>
         * **Limit:** 1 to 3
         */
        phones?: Agent.Phones.Item[];
        /**
         * List of urls. <br><br>
         * **Limit:** 1 to 3
         */
        websites?: Agent.Websites.Item[];
    }

    export namespace Agent {
        export type Emails = Emails.Item[];

        export namespace Emails {
            export interface Item {
                /** Email attached to the agent. */
                email?: string;
                /** Label for the email. */
                label?: string;
            }
        }

        export type Phones = Phones.Item[];

        export namespace Phones {
            export interface Item {
                /** Label for the phone number. */
                label?: string;
                /** Phone number attached to the agent in E.164 format. */
                phone?: string;
            }
        }

        export type Websites = Websites.Item[];

        export namespace Websites {
            export interface Item {
                /** Label for the url. */
                label?: string;
                /** Url attached to the agent. */
                url?: string;
            }
        }
    }

    /**
     * Legal documentation links.
     */
    export interface Links {
        /** Privacy policy URL. */
        privacyPolicy?: string;
        /** Terms of service URL. */
        termsOfService?: string;
    }

    /**
     * Use case classification for the campaign.
     */
    export interface UseCase {
        /** Detailed summary of what the brand is and how this agent will be used. See the [Use Case Behavior](/guides/campaigns/rcs-compliance#use-case-behavior) section for requirements. */
        behavior?: string;
        value?: Pinnacle.RcsCampaignUseCaseEnum;
    }

    export interface Keywords {
        HELP?: Keywords.Help;
        OPT_IN?: Keywords.OptIn;
        OPT_OUT?: Keywords.OptOut;
    }

    export namespace Keywords {
        export interface Help {
            /** Message sent when a user sends HELP. Must include at least one support contact method (phone, email, or website). See the [Keyword Response Messages](/guides/campaigns/rcs-compliance#keyword-response-messages) section for requirements. */
            message?: string;
            /** Keywords that trigger help response (HELP, SUPPORT, INFO, etc). */
            keywords?: string[];
        }

        export interface OptIn {
            /** Message sent when a user opts in. Must include brand name, confirmation of subscription, and disclosures (STOP and HELP instructions, message and data rates). See the [Keyword Response Messages](/guides/campaigns/rcs-compliance#keyword-response-messages) section for requirements. */
            message?: string;
            /** Keywords that trigger opt-in response (START, SUBSCRIBE, JOIN, etc). */
            keywords?: string[];
        }

        export interface OptOut {
            /** Message sent when a user opts out. Must include brand name, acknowledge opt-out request, and state user will not receive further messages. No marketing or re-engagement attempts. See the [Keyword Response Messages](/guides/campaigns/rcs-compliance#keyword-response-messages) section for requirements. */
            message?: string;
            /** Keywords that trigger opt-out response (END, UNSUBSCRIBE, STOP, etc). */
            keywords?: string[];
        }
    }

    export interface Traffic {
        /** Estimated monthly website visitors. */
        monthlyWebsite?: number;
        /** Estimated monthly RCS messages sent. */
        monthlyRcsEstimate?: number;
    }
}
