// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface CreateStreamTokenParams {
    /** Whether this WebSocket may send call commands. Defaults to true. */
    commands_enabled?: boolean;
    /** Customer-chosen stream ID for reconnects and multiple subscribers. */
    stream_id?: string;
    /** Enable recording for this WebSocket stream. */
    record?: boolean;
}
