// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../../../../index.js";

/**
 * @example
 *     {
 *         to: "to",
 *         from: "from"
 *     }
 */
export interface CreateCallParams {
    /** Destination phone number in E.164 format. */
    to: string;
    /** Voice-enabled phone number owned by your team. */
    from: string;
    /** Start recording as soon as the call stream connects. */
    record?: boolean;
    metadata?: Pinnacle.CallMetadata;
}
