// This file was auto-generated by Fern from our API Definition.

import * as Pinnacle from "../../src/api/index";
import { PinnacleClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Audiences", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "aud_abc123",
            name: "VIP Customers",
            description: "Our most valuable customers",
            contacts: [
                {
                    description: "Premium customer",
                    email: "john@example.com",
                    id: "co_def456",
                    name: "John Doe",
                    phoneNumber: "+12125551234",
                    tags: ["vip", "enterprise"],
                },
            ],
            contactCount: 150,
            pagination: { page: 1, limit: 50, total: 150, hasMore: true },
        };
        server.mockEndpoint().get("/audiences").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.audiences.get({
            id: "aud_abc123",
        });
        expect(response).toEqual({
            id: "aud_abc123",
            name: "VIP Customers",
            description: "Our most valuable customers",
            contacts: [
                {
                    description: "Premium customer",
                    email: "john@example.com",
                    id: "co_def456",
                    name: "John Doe",
                    phoneNumber: "+12125551234",
                    tags: ["vip", "enterprise"],
                },
            ],
            contactCount: 150,
            pagination: {
                page: 1,
                limit: 50,
                total: 150,
                hasMore: true,
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "aud_abc123",
            name: "VIP Customers",
            description: "Our most valuable customers",
            contactCount: 150,
        };
        server.mockEndpoint().get("/audiences").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.audiences.get({
            id: "aud_abc123",
        });
        expect(response).toEqual({
            id: "aud_abc123",
            name: "VIP Customers",
            description: "Our most valuable customers",
            contactCount: 150,
        });
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/audiences").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.audiences.get({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/audiences").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.audiences.get({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/audiences").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.audiences.get({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.ForbiddenError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/audiences").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.audiences.get({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.NotFoundError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/audiences").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.audiences.get({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "Marketing Campaign Q1", description: "Contacts for Q1 marketing push" };
        const rawResponseBody = {
            id: "aud_abc123",
            name: "Marketing Campaign Q1",
            description: "Contacts for Q1 marketing push",
            contactCount: 2,
        };
        server
            .mockEndpoint()
            .post("/audiences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.audiences.create({
            name: "Marketing Campaign Q1",
            description: "Contacts for Q1 marketing push",
        });
        expect(response).toEqual({
            id: "aud_abc123",
            name: "Marketing Campaign Q1",
            description: "Contacts for Q1 marketing push",
            contactCount: 2,
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "VIP Customers",
            description: "Our best customers",
            contacts: ["+12125551234", "+13105551234"],
        };
        const rawResponseBody = {
            id: "aud_abc123",
            name: "Marketing Campaign Q1",
            description: "Contacts for Q1 marketing push",
            contactCount: 2,
        };
        server
            .mockEndpoint()
            .post("/audiences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.audiences.create({
            name: "VIP Customers",
            description: "Our best customers",
            contacts: ["+12125551234", "+13105551234"],
        });
        expect(response).toEqual({
            id: "aud_abc123",
            name: "Marketing Campaign Q1",
            description: "Contacts for Q1 marketing push",
            contactCount: 2,
        });
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "Mixed Audience", contacts: ["+12125551234", "co_abc123", "+13105551234"] };
        const rawResponseBody = {
            id: "aud_abc123",
            name: "Marketing Campaign Q1",
            description: "Contacts for Q1 marketing push",
            contactCount: 2,
        };
        server
            .mockEndpoint()
            .post("/audiences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.audiences.create({
            name: "Mixed Audience",
            contacts: ["+12125551234", "co_abc123", "+13105551234"],
        });
        expect(response).toEqual({
            id: "aud_abc123",
            name: "Marketing Campaign Q1",
            description: "Contacts for Q1 marketing push",
            contactCount: 2,
        });
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/audiences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.audiences.create({
                name: "x",
            });
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/audiences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.audiences.create({
                name: "x",
            });
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/audiences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.audiences.create({
                name: "x",
            });
        }).rejects.toThrow(Pinnacle.ForbiddenError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/audiences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.audiences.create({
                name: "x",
            });
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true };
        server.mockEndpoint().delete("/audiences").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.audiences.delete({
            id: "aud_abc123",
        });
        expect(response).toEqual({
            success: true,
        });
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/audiences").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.audiences.delete({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().delete("/audiences").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.audiences.delete({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().delete("/audiences").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.audiences.delete({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.ForbiddenError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/audiences").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.audiences.delete({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.NotFoundError);
    });

    test("delete (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().delete("/audiences").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.audiences.delete({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { id: "aud_abc123", name: "Updated Audience Name", description: "New description" };
        const rawResponseBody = {
            id: "aud_abc123",
            name: "Updated Audience Name",
            description: "New description",
            contactCount: 150,
        };
        server
            .mockEndpoint()
            .patch("/audiences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.audiences.update({
            id: "aud_abc123",
            name: "Updated Audience Name",
            description: "New description",
        });
        expect(response).toEqual({
            id: "aud_abc123",
            name: "Updated Audience Name",
            description: "New description",
            contactCount: 150,
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { id: "id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/audiences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.audiences.update({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { id: "id" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .patch("/audiences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.audiences.update({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { id: "id" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .patch("/audiences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.audiences.update({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { id: "id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/audiences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.audiences.update({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { id: "id" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .patch("/audiences")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.audiences.update({
                id: "id",
            });
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });
});
