/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { PinnacleClient } from "../../src/Client";
import * as Pinnacle from "../../src/api/index";

describe("Contacts", () => {
    test("get (28c97ac8)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            description: "Friend from work",
            email: "alvaroope@pinnacle.sh",
            id: 137,
            name: "Alva Roope",
            phoneNumber: "+14154537890",
            tags: ["friend", "work"],
        };
        server.mockEndpoint().get("/contacts").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.contacts.get();
        expect(response).toEqual({
            description: "Friend from work",
            email: "alvaroope@pinnacle.sh",
            id: 137,
            name: "Alva Roope",
            phoneNumber: "+14154537890",
            tags: ["friend", "work"],
        });
    });

    test("get (c60dd33b)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/contacts").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.get();
        }).rejects.toThrow(
            new Pinnacle.BadRequestError({
                key: "value",
            }),
        );
    });

    test("get (41311a9b)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/contacts").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.get();
        }).rejects.toThrow(
            new Pinnacle.UnauthorizedError({
                error: "error",
            }),
        );
    });

    test("get (8fa731b7)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/contacts").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.get();
        }).rejects.toThrow(
            new Pinnacle.NotFoundError({
                error: "error",
            }),
        );
    });

    test("get (9aebfd47)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };
        server.mockEndpoint().get("/contacts").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.contacts.get();
        }).rejects.toThrow(
            new Pinnacle.InternalServerError({
                error: "error",
            }),
        );
    });

    test("create (3c4d64cf)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { phoneNumber: "phoneNumber" };
        const rawResponseBody = { id: 137 };
        server
            .mockEndpoint()
            .post("/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.create({
            phoneNumber: "phoneNumber",
        });
        expect(response).toEqual({
            id: 137,
        });
    });

    test("create (45bc682c)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            phoneNumber: "phoneNumber",
            description: undefined,
            email: undefined,
            name: undefined,
            tags: undefined,
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.create({
                phoneNumber: "phoneNumber",
                description: undefined,
                email: undefined,
                name: undefined,
                tags: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.BadRequestError({
                key: "value",
            }),
        );
    });

    test("create (e5b13586)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            phoneNumber: "phoneNumber",
            description: undefined,
            email: undefined,
            name: undefined,
            tags: undefined,
        };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.create({
                phoneNumber: "phoneNumber",
                description: undefined,
                email: undefined,
                name: undefined,
                tags: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.UnauthorizedError({
                error: "error",
            }),
        );
    });

    test("create (6a7c5c8a)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            phoneNumber: "phoneNumber",
            description: undefined,
            email: undefined,
            name: undefined,
            tags: undefined,
        };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.create({
                phoneNumber: "phoneNumber",
                description: undefined,
                email: undefined,
                name: undefined,
                tags: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.InternalServerError({
                error: "error",
            }),
        );
    });

    test("update (c19e83b1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            description: "Retired",
            email: "alvaroopedtech@pinnacle.sh",
            name: "Retired Bestie",
            tags: ["friend"],
            id: 137,
        };
        const rawResponseBody = { id: 137 };
        server
            .mockEndpoint()
            .put("/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contacts.update({
            description: "Retired",
            email: "alvaroopedtech@pinnacle.sh",
            name: "Retired Bestie",
            tags: ["friend"],
            id: 137,
        });
        expect(response).toEqual({
            id: 137,
        });
    });

    test("update (4d77ccb7)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { id: 1, description: undefined, email: undefined, name: undefined, tags: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.update({
                id: 1,
                description: undefined,
                email: undefined,
                name: undefined,
                tags: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.BadRequestError({
                key: "value",
            }),
        );
    });

    test("update (cfd9282f)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { id: 1, description: undefined, email: undefined, name: undefined, tags: undefined };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .put("/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.update({
                id: 1,
                description: undefined,
                email: undefined,
                name: undefined,
                tags: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.UnauthorizedError({
                error: "error",
            }),
        );
    });

    test("update (c143669b)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { id: 1, description: undefined, email: undefined, name: undefined, tags: undefined };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .put("/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.update({
                id: 1,
                description: undefined,
                email: undefined,
                name: undefined,
                tags: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.NotFoundError({
                error: "error",
            }),
        );
    });

    test("update (7ea7510b)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { id: 1, description: undefined, email: undefined, name: undefined, tags: undefined };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .put("/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contacts.update({
                id: 1,
                description: undefined,
                email: undefined,
                name: undefined,
                tags: undefined,
            });
        }).rejects.toThrow(
            new Pinnacle.InternalServerError({
                error: "error",
            }),
        );
    });
});
