/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { PinnacleClient } from "../../src/Client";

describe("PinnacleClient", () => {
    test("getRCSFunctionality", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            is_enabled: true,
            standalone_rich_card: true,
            carousel_rich_card: true,
            create_calendar_event_action: true,
            dial_action: true,
            open_url_action: true,
            share_location_action: true,
            view_location_action: true,
        };
        server.mockEndpoint().get("/rcs_functionality").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.getRcsFunctionality();
        expect(response).toEqual({
            is_enabled: true,
            standalone_rich_card: true,
            carousel_rich_card: true,
            create_calendar_event_action: true,
            dial_action: true,
            open_url_action: true,
            share_location_action: true,
            view_location_action: true,
        });
    });
});
