/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { PinnacleClient } from "../../src/Client";

describe("Messages", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            content: { text: "Hello from Pinnacle" },
            cost: 10,
            deliveredAt: "deliveredAt",
            error: '{"message": "Error: Timeout occurred"}',
            id: 1240,
            method: "API",
            numSegments: 1,
            receiver: "+1415654321",
            sender: "+1415567890",
            sentAt: "2025-06-18T21:27:13.809",
            status: "PENDING",
            type: "SMS",
        };
        server.mockEndpoint().get("/messages/1240").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.messages.get(1240);
        expect(response).toEqual({
            content: {
                text: "Hello from Pinnacle",
            },
            cost: 10,
            deliveredAt: "deliveredAt",
            error: '{"message": "Error: Timeout occurred"}',
            id: 1240,
            method: "API",
            numSegments: 1,
            receiver: "+1415654321",
            sender: "+1415567890",
            sentAt: "2025-06-18T21:27:13.809",
            status: "PENDING",
            type: "SMS",
        });
    });
});
