/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const PinnacleEnvironment = {
    Default: "https://api.pinnacle.sh",
} as const;

export type PinnacleEnvironment = typeof PinnacleEnvironment.Default;
