// This file was auto-generated by Fern from our API Definition.

import type * as Pinnacle from "../../../../../../index.js";

/**
 * @example
 *     {
 *         phones: ["+14155550123", "+14155559876", "+14155550111"],
 *         campaignType: "TOLL_FREE",
 *         campaignId: "tf_1234567890"
 *     }
 */
export interface AttachCampaignParams {
    /**
     * List of phone number (E.164 format). <br><br>
     * **Limit:** 1 to 10
     */
    phones: string[];
    campaignType: Pinnacle.MessagingProfileEnum;
    /**
     * Unique identifier for the campaign. <br>
     *
     *  - **TOLL_FREE** campaigns:
     *    - Must begin with the prefix `tf_`
     *    - Example: `tf_1234567890`
     *  - **10DLC** campaigns:
     *    - Must begin with the prefix `dlc_`
     *    - Example: `dlc_1234567890`
     */
    campaignId: string;
}
