/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool";
import { PinnacleClient } from "../../../src/Client";

describe("Mms", () => {
    test("send", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            from: "+14155164736",
            mediaUrls: [
                "https://fastly.picsum.photos/id/941/300/300.jpg?hmac=mDxM9PWSqRDjecwSCEpzU4bj35gqnG7yA25OL29uNv0",
            ],
            options: { multiple_messages: true, validate: true },
            text: "Check out this image!",
            to: "+14154746461",
        };
        const rawResponseBody = {
            messageIds: [101, 102],
            segments: 3,
            totalCost: 0.09,
            sender: "+14155164736",
            recipient: "+14154746461",
            status: "queued",
        };
        server
            .mockEndpoint()
            .post("/messages/send/mms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.messages.mms.send({
            from: "+14155164736",
            mediaUrls: [
                "https://fastly.picsum.photos/id/941/300/300.jpg?hmac=mDxM9PWSqRDjecwSCEpzU4bj35gqnG7yA25OL29uNv0",
            ],
            options: {
                multiple_messages: true,
                validate: true,
            },
            text: "Check out this image!",
            to: "+14154746461",
        });
        expect(response).toEqual({
            messageIds: [101, 102],
            segments: 3,
            totalCost: 0.09,
            sender: "+14155164736",
            recipient: "+14154746461",
            status: "queued",
        });
    });
});
