// This file was auto-generated by Fern from our API Definition.

import * as Pinnacle from "../../../src/api/index";
import { PinnacleClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("Sms", () => {
    test("send (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { from: "+14155164736", text: "Hey!", to: "+14154746461" };
        const rawResponseBody = {
            messageId: "msg_1234567890",
            segments: { count: 1, encoding: "gsm7" },
            totalCost: 10,
            sender: "+14155164736",
            recipient: "+14154746461",
            status: "queued",
        };
        server
            .mockEndpoint()
            .post("/messages/send/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.messages.sms.send({
            from: "+14155164736",
            text: "Hey!",
            to: "+14154746461",
        });
        expect(response).toEqual({
            messageId: "msg_1234567890",
            segments: {
                count: 1,
                encoding: "gsm7",
            },
            totalCost: 10,
            sender: "+14155164736",
            recipient: "+14154746461",
            status: "queued",
        });
    });

    test("send (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { from: "+14155164736", text: "Hey!", to: "+14154746461" };
        const rawResponseBody = {
            scheduleId: "msg_sched_1234567890",
            config: {
                sendAt: "2024-08-01T09:00:00",
                recurrence: "cron(0 9 * * MON-FRI *)",
                timezone: "UTC",
                endDate: "endDate",
            },
        };
        server
            .mockEndpoint()
            .post("/messages/send/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.messages.sms.send({
            from: "+14155164736",
            text: "Hey!",
            to: "+14154746461",
        });
        expect(response).toEqual({
            scheduleId: "msg_sched_1234567890",
            config: {
                sendAt: "2024-08-01T09:00:00",
                recurrence: "cron(0 9 * * MON-FRI *)",
                timezone: "UTC",
                endDate: "endDate",
            },
        });
    });

    test("send (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { from: "from", text: "text", to: "to" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/messages/send/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.messages.sms.send({
                from: "from",
                text: "text",
                to: "to",
            });
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("send (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { from: "from", text: "text", to: "to" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/messages/send/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.messages.sms.send({
                from: "from",
                text: "text",
                to: "to",
            });
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("send (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { from: "from", text: "text", to: "to" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/messages/send/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.messages.sms.send({
                from: "from",
                text: "text",
                to: "to",
            });
        }).rejects.toThrow(Pinnacle.PaymentRequiredError);
    });

    test("send (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { from: "from", text: "text", to: "to" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/messages/send/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.messages.sms.send({
                from: "from",
                text: "text",
                to: "to",
            });
        }).rejects.toThrow(Pinnacle.ForbiddenError);
    });

    test("send (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { from: "from", text: "text", to: "to" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/messages/send/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.messages.sms.send({
                from: "from",
                text: "text",
                to: "to",
            });
        }).rejects.toThrow(Pinnacle.NotFoundError);
    });

    test("send (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { from: "from", text: "text", to: "to" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/messages/send/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.messages.sms.send({
                from: "from",
                text: "text",
                to: "to",
            });
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });

    test("send (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { from: "from", text: "text", to: "to" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/messages/send/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(501)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.messages.sms.send({
                from: "from",
                text: "text",
                to: "to",
            });
        }).rejects.toThrow(Pinnacle.NotImplementedError);
    });

    test("validate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "Hello from Pinnacle" };
        const rawResponseBody = {
            isOverSegmentLimit: false,
            segments: {
                gsm7: { totalBytes: 11, unsupported: ["unsupported"], value: ["Hello from Pinnacle"] },
                utf16: { totalBytes: 24, value: ["Hello from Pinnacle"] },
            },
            total: { gsm7: 0.01, utf16: 0.01 },
            unit: 0.01,
        };
        server
            .mockEndpoint()
            .post("/messages/validate/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.messages.sms.validate({
            text: "Hello from Pinnacle",
        });
        expect(response).toEqual({
            isOverSegmentLimit: false,
            segments: {
                gsm7: {
                    totalBytes: 11,
                    unsupported: ["unsupported"],
                    value: ["Hello from Pinnacle"],
                },
                utf16: {
                    totalBytes: 24,
                    value: ["Hello from Pinnacle"],
                },
            },
            total: {
                gsm7: 0.01,
                utf16: 0.01,
            },
            unit: 0.01,
        });
    });

    test("validate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "text" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/messages/validate/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.messages.sms.validate({
                text: "text",
            });
        }).rejects.toThrow(Pinnacle.BadRequestError);
    });

    test("validate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "text" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/messages/validate/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.messages.sms.validate({
                text: "text",
            });
        }).rejects.toThrow(Pinnacle.UnauthorizedError);
    });

    test("validate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "text" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/messages/validate/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.messages.sms.validate({
                text: "text",
            });
        }).rejects.toThrow(Pinnacle.ForbiddenError);
    });

    test("validate (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PinnacleClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { text: "text" };
        const rawResponseBody = { error: "error" };
        server
            .mockEndpoint()
            .post("/messages/validate/sms")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.messages.sms.validate({
                text: "text",
            });
        }).rejects.toThrow(Pinnacle.InternalServerError);
    });
});
